Repository easybuilders/easybuild-framework, pull requests merged in 2018-08, with the labels that each got.

#2547 filter out patched files in test/ in fetch_easyconfigs_from_pr
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#2549 allow skipping sanity check
  easybuild/framework/easyblock.py
  test/framework/options.py
Labels: change, enhancement

#2540 Add support for BLIS and goblf toolchain that uses BLIS for BLAS.
  easybuild/toolchains/goblf.py
  easybuild/toolchains/linalg/blis.py
Labels: enhancement

#2464 Add goolfc-2.6.10 toolchain for test_get_toolchain_hierarchy robot test.
  test/framework/easyconfigs/test_ecs/f/FFTW/FFTW-3.3.3-GCC-4.8.2-serial.eb
  test/framework/easyconfigs/test_ecs/f/FFTW/FFTW-3.3.3-gompic-2.6.10.eb
  test/framework/easyconfigs/test_ecs/g/gcccuda/gcccuda-2.6.10.eb
  test/framework/easyconfigs/test_ecs/g/golf/golf-2.6.10.eb
  test/framework/easyconfigs/test_ecs/g/golfc/golfc-2.6.10.eb
  test/framework/easyconfigs/test_ecs/g/gompic/gompic-2.6.10.eb
  test/framework/easyconfigs/test_ecs/g/goolfc/goolfc-2.6.10.eb
  test/framework/easyconfigs/test_ecs/h/hwloc/hwloc-1.8-gcccuda-2.6.10.eb
  test/framework/easyconfigs/test_ecs/o/OpenBLAS/OpenBLAS-0.2.8-GCC-4.8.2-LAPACK-3.4.2.eb
  test/framework/easyconfigs/test_ecs/o/OpenMPI/OpenMPI-1.7.3-gcccuda-2.6.10.eb
  test/framework/easyconfigs/test_ecs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompic-2.6.10-OpenBLAS-0.2.8-LAPACK-3.4.2.eb
  test/framework/filetools.py
  test/framework/robot.py
  test/framework/scripts.py
Labels: enhancement

#2465 Use GCC instead of gompi for OpenBLAS in goolf-1.4.10 test toolchain.
  test/framework/easyconfigparser.py
  test/framework/easyconfigs/test_ecs/f/FFTW/FFTW-3.3.3-GCC-4.7.2-serial.eb
  test/framework/easyconfigs/test_ecs/g/golf/golf-1.4.10.eb
  test/framework/easyconfigs/test_ecs/g/goolf/goolf-1.4.10.eb
  test/framework/easyconfigs/test_ecs/o/OpenBLAS/OpenBLAS-0.2.6-GCC-4.7.2-LAPACK-3.4.2.eb
  test/framework/easyconfigs/test_ecs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-1.4.10-OpenBLAS-0.2.6-LAPACK-3.4.2.eb
  test/framework/easyconfigs/v2.0/goolf.eb
  test/framework/easyconfigs/yeb/goolf-1.4.10.yeb
  test/framework/options.py
  test/framework/robot.py
Labels: change

#2554 Check gc3pie version using the `pkg_resources` API.
  easybuild/tools/job/gc3pie.py
Labels: bug fix

#2474 make GC3Pie stop build process if a dependency failed (fix for #1441)
  easybuild/tools/job/gc3pie.py
Labels: bug fix
