Repository easybuilders/easybuild-framework, pull requests merged in 2018-02, with the labels that each got.

#2398 avoid fatal error when determining glibc version on non-glibc Linux system (e.g. Alphine Linux)
  easybuild/tools/systemtools.py
  test/framework/systemtools.py
Labels: bug fix, enhancement

#2379 Add pagination support in clean_gists.py
  easybuild/scripts/clean_gists.py
Labels: enhancement

#2374 Added functionality to skip devel module with naming scheme
  easybuild/framework/easyblock.py
  easybuild/tools/module_naming_scheme/mns.py
Labels: enhancement

#2410 exclude location of RPATH wrappers from $PATH to avoid fork bomb
  easybuild/scripts/rpath_wrapper_template.sh.in
  easybuild/tools/toolchain/toolchain.py
  test/framework/toy_build.py
Labels: bug fix

#2409 declare support for RPATH linking stable
  easybuild/tools/toolchain/toolchain.py
Labels: change, enhancement

#2392 Initial set of OHPC module meta data for EasyBuild
  etc/ohpc_external_modules_metadata.cfg
Labels: enhancement
