Repository easybuilders/easybuild-framework, pull requests merged in 2018-11, with the labels that each got.

#2643 don't pass down specific environment variables into submitted jobs
  easybuild/tools/parallelbuild.py
Labels: bug fix, change

#2649 fix lib64 fallback for 'lib'/'lib64' dirs entry in sanity_check_paths
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#2650 change PGI F90 Fortran compiler to pgf90
  easybuild/toolchains/compiler/pgi.py
  test/framework/toolchain.py
Labels: bug fix, change

#2642 add support for using Slurm as backend for --job
  easybuild/tools/config.py
  easybuild/tools/job/gc3pie.py
  easybuild/tools/job/pbs_python.py
  easybuild/tools/job/slurm.py
  easybuild/tools/options.py
  test/framework/parallelbuild.py
Labels: enhancement

#2644 always skip symlinks in adjust_permissions
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: change

#2651 use --set-upstream-to in install-EasyBuild-develop.sh script to deal with deprecated/no longer support --set-upstream
  easybuild/scripts/install-EasyBuild-develop.sh
Labels: bug fix

#2648 update template constants to use https
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
  test/framework/easyconfigs/test_ecs/g/gzip/gzip-1.4.eb
  test/framework/easyconfigs/v1.0/g/gzip/gzip-1.4.eb
  test/framework/easyconfigs/v1.0/g/gzip/gzip-1.5-goolf-1.4.10.eb
  test/framework/easyconfigs/v1.0/g/gzip/gzip-1.5-ictce-4.1.13.eb
Labels: bug fix, change

#2656 add support for deprecating easyconfig files & toolchains
  easybuild/framework/easyconfig/default.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/tools/build_log.py
  easybuild/tools/toolchain/toolchain.py
  test/framework/build_log.py
  test/framework/easyconfig.py
  test/framework/options.py
Labels: enhancement

#2657 changed easyconfig.update to be able to specify not to allow duplicate values
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: enhancement

#2660 fix order of keys in 'toolchain' value for dumped easyconfig file (name, version) + run style check on dumped easyconfigs in dump tests
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/one.py
  test/framework/easyconfig.py
Labels: bug fix

#2635 fixing bug that could cause to silently overwrite an existing easyconfig
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/tweak.py
  easybuild/tools/filetools.py
  test/framework/filetools.py
  test/framework/tweak.py
Labels: bug fix

#2663 flesh out 'avail_easyblocks' function from support for --list-easyblocks'
  easybuild/framework/easyconfig/tools.py
  easybuild/tools/docs.py
  easybuild/tools/utilities.py
  test/framework/easyblock.py
  test/framework/options.py
Labels: code cleanup, enhancement

#2666 specify filename pattern for output file of jobs submitted to Slurm
  easybuild/tools/job/slurm.py
  test/framework/parallelbuild.py
Labels: change, enhancement

#2667 deprecate the ictce toolchain
  easybuild/toolchains/ictce.py
  test/framework/docs.py
  test/framework/easyconfig.py
  test/framework/easyconfigs/test_ecs/__archive__/i/intel/intel-2012a.eb
  test/framework/easyconfigs/test_ecs/g/gzip/gzip-1.5-intel-2018a.eb
  test/framework/easyconfigs/test_ecs/i/ictce/ictce-4.1.13.eb
  test/framework/easyconfigs/test_ecs/i/intel/intel-2018a.eb
  test/framework/easyconfigs/test_ecs/p/Python/Python-2.7.10-intel-2018a.eb
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-deps.eb
  test/framework/easyconfigs/v1.0/g/gzip/gzip-1.5-intel-2018a.eb
  test/framework/easyconfigs/v2.0/doesnotexist.eb
  test/framework/easyconfigs/v2.0/gzip.eb
  test/framework/easyconfigs/v2.0/libpng.eb
  test/framework/easyconfigs/yeb/Python-2.7.10-intel-2018a.yeb
  test/framework/easyconfigs/yeb/intel-2018a.yeb
  test/framework/module_generator.py
  test/framework/modules/icc/2018.1.163
  test/framework/modules/iccifort/2011.13.367
  test/framework/modules/iccifort/2018.1.163
  test/framework/modules/ifort/2018.1.163
  test/framework/modules/imkl/2018.1.163
  test/framework/modules/impi/2018.1.163
  test/framework/modules/intel/2012a
  test/framework/modules/intel/2018a
  test/framework/options.py
  test/framework/parallelbuild.py
  test/framework/robot.py
  test/framework/sandbox/easybuild/tools/module_naming_scheme/test_module_naming_scheme.py
  test/framework/scripts.py
  test/framework/toolchain.py
  test/framework/toy_build.py
  test/framework/yeb.py
Labels: change

#2357 support use of version ranges in --filter-deps
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/options.py
Labels: enhancement

#2653 Archive easyblocks along with easyconfig
  easybuild/framework/easyblock.py
  test/framework/options.py
  test/framework/sandbox/easybuild/easyblocks/t/toytoy.py
  test/framework/toy_build.py
Labels: bug fix, enhancement

#2400 add support for --list-prs (REVIEW)
  easybuild/main.py
  easybuild/tools/github.py
  easybuild/tools/options.py
  test/framework/github.py
  test/framework/options.py
Labels: enhancement

#2595 allow setting optarch compiler flags in the easyconfig
  easybuild/tools/toolchain/compiler.py
  test/framework/toolchain.py
Labels: enhancement

#2668 use github_user in test_list_prs
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#2670 make print functions more robust w.r.t. arguments being passed to format the message to be printed
  easybuild/tools/build_log.py
  test/framework/build_log.py
Labels: change, enhancement
