Repository easybuilders/easybuild-framework, pull requests merged in 2018-07, with the labels that each got.

#2479 initial work on docker containerization support
  .gitignore
  easybuild/main.py
  easybuild/tools/config.py
  easybuild/tools/containers.py
  easybuild/tools/containers/__init__.py
  easybuild/tools/containers/base.py
  easybuild/tools/containers/common.py
  easybuild/tools/containers/docker.py
  easybuild/tools/containers/singularity.py
  easybuild/tools/containers/utils.py
  setup.py
  test/framework/containers.py
Labels: containers

#2395 Add module load time env var to user module path
  easybuild/framework/easyblock.py
  easybuild/tools/module_generator.py
  test/framework/easyblock.py
  test/framework/module_generator.py
Labels: enhancement

#2525 add 'bitbucket_account' easyconfig parameter and template and let BITBUCKET* templates use it
  easybuild/framework/easyconfig/default.py
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
Labels: enhancement

#2529 bump version to 3.6.2 & update release notes
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2532 release EasyBuild v3.6.2
  .flake8.ini
  .gitignore
  .hound.yml
  .travis.yml
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/one.py
  easybuild/framework/easyconfig/templates.py
  easybuild/main.py
  easybuild/scripts/bootstrap_eb.py
  easybuild/tools/config.py
  easybuild/tools/containers.py
  easybuild/tools/containers/__init__.py
  easybuild/tools/containers/base.py
  easybuild/tools/containers/common.py
  easybuild/tools/containers/docker.py
  easybuild/tools/containers/singularity.py
  easybuild/tools/containers/utils.py
  easybuild/tools/module_generator.py
  easybuild/tools/options.py
  easybuild/tools/version.py
  setup.cfg
  setup.py
  test/framework/config.py
  test/framework/containers.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/module_generator.py
  test/framework/sandbox/not_an_easyconfig.eb
  test/framework/toy_build.py
Labels: update

#2533 sync with master & bump version to 3.6.3dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update
