Repository easybuilders/easybuild-framework, pull requests merged in 2018-03, with the labels that each got.

#2420 temporarily disable test suite runs for environment modules
  .travis.yml
Labels: change request

#2419 fix target account for --update-pr in case it's different from GitHub account being used to push branch
  easybuild/tools/github.py
  test/framework/options.py
Labels: bug fix

#2416 bump version to 3.5.2 & update release notes
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2422 release EasyBuild v3.5.2
  .travis.yml
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/scripts/bootstrap_eb.py
  easybuild/scripts/clean_gists.py
  easybuild/scripts/rpath_wrapper_template.sh.in
  easybuild/tools/github.py
  easybuild/tools/module_naming_scheme/mns.py
  easybuild/tools/systemtools.py
  easybuild/tools/toolchain/compiler.py
  easybuild/tools/toolchain/toolchain.py
  easybuild/tools/version.py
  etc/ohpc_external_modules_metadata.cfg
  test/framework/options.py
  test/framework/systemtools.py
  test/framework/toolchain.py
  test/framework/toy_build.py
Labels: update

#2424 sync with master + bump to 3.6.0dev
  .travis.yml
  RELEASE_NOTES
  easybuild/tools/github.py
  easybuild/tools/version.py
  test/framework/options.py
Labels: update

#2425 re-enable testing against environment modules, bump Lmod to 7.7.16
  .travis.yml
Labels: change

#2426 fix target account for branch pushed when using --new-pr
  easybuild/tools/github.py
  test/framework/options.py
Labels: bug fix

#2427 Print which hook is being executed in the command line output
  easybuild/tools/hooks.py
  test/framework/hooks.py
  test/framework/toy_build.py
Labels: enhancement

#2421 fix order in result of gen_list_easyblocks and gen_easyblocks_overview_rst
  easybuild/tools/docs.py
  test/framework/docs.py
  test/framework/options.py
  test/framework/sandbox/easybuild/easyblocks/generic/configuremake.py
Labels: bug fix

#2429 bump version to 3.5.3 & update release notes
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2430 release EasyBuild v3.5.3
  .travis.yml
  RELEASE_NOTES
  easybuild/tools/docs.py
  easybuild/tools/github.py
  easybuild/tools/hooks.py
  easybuild/tools/version.py
  test/framework/docs.py
  test/framework/hooks.py
  test/framework/options.py
  test/framework/sandbox/easybuild/easyblocks/generic/configuremake.py
  test/framework/toy_build.py
Labels: update

#2431 sync with master after EasyBuild v3.5.3 release
  RELEASE_NOTES
Labels: update

#2435 enable caching of $HOME/.cache/pip in Travis config
  .travis.yml
Labels: enhancement

#2434 avoid that '--inject-checksums' adds lines longer than 120 characters
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/style.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-deps.eb
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-gompi-1.3.12-test.eb
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-iter.eb
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-multiple.eb
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0.eb
  test/framework/easyconfigs/yeb/toy-0.0.yeb
  test/framework/filetools.py
  test/framework/github.py
  test/framework/options.py
  test/framework/sandbox/sources/toy/extensions/bar-0.0_fix-silly-typo-in-printf-statement.patch
  test/framework/sandbox/sources/toy/toy-0.0_fix-silly-typo-in-printf-statement.patch
  test/framework/toy_build.py
Labels: enhancement

#2432 determine whether included easyblocks are generic or not based on class they define
  easybuild/tools/include.py
  test/framework/include.py
  test/framework/options.py
Labels: bug fix

#2436 make sure GitHub token is used in test for --preview-pr
  test/framework/options.py
Labels: bug fix

#2438 loosen commit message requirements w.r.t. to patches as long as all easyconfigs are new
  easybuild/tools/github.py
Labels: enhancement

#2443 test for custom commit message when deleting a file instead of when adding a patch
  test/framework/options.py
Labels: bug fix

#2444 make diff_stat pattern also match output of older git versions in tests for --new/update-pr
  test/framework/options.py
Labels: enhancement

#2446 Replace raw strings with bytes literal as iterator sentinels in checksum calculation
  easybuild/tools/filetools.py
Labels: enhancement

#2440 take into account that toolchain components may be hidden when determining toolchain composition
  easybuild/tools/module_naming_scheme/toolchain.py
Labels: bug fix

#2378 New command-line option `--job-max-jobs` to cap nr of submitted build jobs
  easybuild/tools/config.py
  easybuild/tools/job/gc3pie.py
  easybuild/tools/options.py
Labels: enhancement

#2451 add configuration for houndci + flake8
  .flake8.ini
  .hound.yml
  easybuild/tools/github.py
  test/framework/options.py
Labels: enhancement

#2437 add Accept header when downloading file
  easybuild/tools/filetools.py
Labels: enhancement

#2449 include running of 'eb --check-github' in Travis config
  .travis.yml
Labels: enhancement

#2452 flesh out common code blocks in test/framework/options.py
  test/framework/options.py
Labels: enhancement

#2454 specify GitHub login ID used in tests to --check-github in Travis config
  .travis.yml
Labels: bug fix

#2455 Add support for a new toolchain, gomkl.
  easybuild/toolchains/gomkl.py
Labels: enhancement

#2462 stick to autopep8 1.3.4 when testing with Python 2.6
  .travis.yml
Labels: bug fix

#2442 add force_in_dry_run=True to copy_file in copy_patch_files
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/options.py
Labels: bug fix

#2384 automatically add 'new' and/or 'update' labels in --new-pr
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/tools/github.py
  test/framework/easyconfig.py
Labels: enhancement

#2388 include -ftree-vectorize and -fno-math-errno in default compiler optimisation flags for GCC
  easybuild/toolchains/compiler/clang.py
  easybuild/toolchains/compiler/gcc.py
  easybuild/toolchains/compiler/ibmxl.py
  easybuild/toolchains/compiler/inteliccifort.py
  easybuild/toolchains/compiler/pgi.py
  easybuild/tools/toolchain/compiler.py
  test/framework/options.py
  test/framework/toolchain.py
Labels: change, enhancement

#2391 support depends_on "load" statements in generated modules via --module-depends-on and module_depends_on easyconfig parameter
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  easybuild/tools/config.py
  easybuild/tools/module_generator.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  test/framework/module_generator.py
  test/framework/options.py
Labels: enhancement

#2458 Introduce golf: compiler toolchain with GCC, OpenBLAS, and FFTW.
  easybuild/toolchains/golf.py
  easybuild/tools/toolchain/toolchain.py
Labels: enhancement

#2460 New compiler+linalg toolchains: pmkl and gmkl (PGI+MKL and GCC+MKL)
  easybuild/toolchains/gmkl.py
  easybuild/toolchains/pmkl.py
Labels: enhancement

#2461 Cuda toolchains gmklc, gomklc, iimklc, iompic, iomklc
  easybuild/toolchains/gmklc.py
  easybuild/toolchains/gomklc.py
  easybuild/toolchains/iimklc.py
  easybuild/toolchains/iomklc.py
  easybuild/toolchains/iompic.py
Labels: enhancement
