Repository easybuilders/easybuild-framework, pull requests merged in 2018-05, with the labels that each got.

#2493 add 'exts_download_dep_fail' as known easyconfig parameter
  easybuild/framework/easyconfig/default.py
Labels: enhancement

#2497 handle missing permissions for adding labels in --new-pr
  easybuild/tools/github.py
Labels: bug fix

#2494 add support for passing custom messages on failing sanity check for extensions
  easybuild/framework/easyblock.py
  easybuild/framework/extension.py
  easybuild/framework/extensioneasyblock.py
  test/framework/easyblock.py
Labels: enhancement

#2498 restore tweaked $TMPDIR value after loading module (for sanity check)
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: bug fix

#2502 enhance get_module_path function to auto-detect generic vs software-specific easyblock class names
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: bug fix

#2477 add support for enabling fallback in sanity check to consider lib64 equivalent for seemingly missing libraries
  easybuild/framework/easyblock.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/toy_build.py
Labels: enhancement

#2506 prepend location for temporary module file to $MODULEPATH with high priority + mark it as default in load_fake_module method
  easybuild/framework/easyblock.py
  easybuild/tools/modules.py
  test/framework/easyblock.py
  test/framework/modules.py
Labels: bug fix

#2507 Add fosscuda toolchain
  easybuild/toolchains/fosscuda.py
Labels: enhancement

#2510 bump version to 3.6.1 & update release notes
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2513 release EasyBuild v3.6.1
  CONTRIBUTING.md
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/templates.py
  easybuild/framework/easyconfig/tweak.py
  easybuild/framework/extension.py
  easybuild/framework/extensioneasyblock.py
  easybuild/toolchains/fosscuda.py
  easybuild/tools/config.py
  easybuild/tools/github.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  easybuild/tools/version.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/modules.py
  test/framework/suite.py
  test/framework/toy_build.py
  test/framework/tweak.py
Labels: update

#2514 sync with master & bump version to 3.6.2dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2511 move flake8 config into setup.cfg + fix style issues in easybuild/tools/options.py
  .flake8.ini
  .hound.yml
  easybuild/tools/options.py
  setup.cfg
Labels: code cleanup

#2518 make test that verifies that BuildOptions does not support updating a bit more flexible
  test/framework/config.py
Labels: change

#2517 fix for offline use of bootstrap script: ignore errors when determining source URLs if source tarballs are provided
  .travis.yml
  easybuild/scripts/bootstrap_eb.py
Labels: bug fix
