Repository easybuilders/easybuild-framework, pull requests merged in 2018-10, with the labels that each got.

#2597 generate .modulerc.lua when Lua syntax and Lmod >= 7.8 is used
  .travis.yml
  easybuild/tools/module_generator.py
  easybuild/tools/modules.py
  test/framework/easyblock.py
  test/framework/module_generator.py
Labels: change, enhancement

#2604 determine file_info for all easyconfigs before any actual copying
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: bug fix

#2602 fix composing of lib64 fallback paths in sanity check
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#2610 add support for disabling modules tool version check
  easybuild/tools/config.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
Labels: enhancement

#2605 Allow --force to use regex if --try-toolchain cannot map intelligently.
  easybuild/framework/easyconfig/tweak.py
Labels: bug fix, enhancement

#2606 also check for module wrappers in 'ModulesTool.exist' method
  easybuild/tools/modules.py
  test/framework/modules.py
Labels: bug fix

#2611 add support for ModuleGenerator.modulerc method to also write .modulerc file + Lmod 6.x specific check
  easybuild/tools/module_generator.py
  test/framework/module_generator.py
Labels: enhancement

#2613 add trailing newline to module load message if it's not there yet
  easybuild/framework/easyblock.py
  easybuild/tools/module_generator.py
  test/framework/module_generator.py
  test/framework/toy_build.py
Labels: bug fix

#2617 retain all dependencies when determining dependency tree of a toolchain
  easybuild/framework/easyconfig/tweak.py
  test/framework/tweak.py
Labels: bug fix

#2619 Protect exts_lists from templating in dump method...
  easybuild/framework/easyconfig/format/format.py
  test/framework/easyconfig.py
Labels: bug fix

#2621 making cuda capability detection more robust
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/robot.py
Labels: bug fix

#2625 release EasyBuild v3.7.1
  .travis.yml
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/format.py
  easybuild/framework/easyconfig/tweak.py
  easybuild/scripts/bootstrap_eb.py
  easybuild/tools/config.py
  easybuild/tools/docs.py
  easybuild/tools/module_generator.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  easybuild/tools/version.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/easyconfigs/v1.0/g/gzip/gzip-1.4.eb
  test/framework/easyconfigs/v1.0/g/gzip/gzip-1.5-ictce-4.1.13.eb
  test/framework/module_generator.py
  test/framework/modules.py
  test/framework/robot.py
  test/framework/toy_build.py
  test/framework/tweak.py
Labels: update

#2626 sync with master after release of EasyBuild v3.7.1 + bump version to 3.7.2dev
  RELEASE_NOTES
  easybuild/framework/easyconfig/tweak.py
  easybuild/tools/version.py
  test/framework/tweak.py
Labels: update

#2629 Add option to skip pre-creation of install directory
  easybuild/framework/easyblock.py
  easybuild/tools/config.py
  easybuild/tools/options.py
Labels: enhancement

#2637 add test for --pre-create-installdir
  test/framework/parallelbuild.py
Labels: bug fix

#2631 make --from-pr always try to apply PR patch on top of PR target branch
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#2638 flesh out setting up of configuration into dedicated 'set_up_configuration' function
  easybuild/main.py
  easybuild/tools/build_log.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/lib.py
  test/framework/suite.py
Labels: change, enhancement

#2641 clean error when 'eb' is cancelled by user
  easybuild/main.py
Labels: enhancement
