Repository easybuilders/easybuild-framework, pull requests merged in 2019-04, with the labels that each got.

#2825 ensure check_conflicts uses flattened list of build dependencies for easyconfigs that use multi_deps
  easybuild/tools/robot.py
Labels: bug fix

#2826 make check_conflicts aware of multi_deps
  easybuild/tools/robot.py
  test/framework/robot.py
Labels: bug fix

#2827 fix crash in dep_graph when easyconfig that uses multi_deps is used
  easybuild/framework/easyconfig/tools.py
  test/framework/easyconfig.py
Labels: bug fix

#2803 use temporary checkout of repository as robot path for --new-pr and --update-pr to determine locations for patch files
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#2828 add support for loading first version listed in multi_deps by default in generated module file
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/extensioneasyblock.py
  easybuild/tools/module_generator.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/module_generator.py
  test/framework/toy_build.py
Labels: enhancement

#2822 Added FFTW_STATIC_LIBS_MT to FFTW_MAP_CLASS. Otherwise FFTW_STATIC_LIBS_MT are incorrectly defined
  easybuild/tools/toolchain/constants.py
  test/framework/toolchain.py
Labels: bug fix

#2732 Sort available version list when selecting/generating easyconfig
  easybuild/framework/easyconfig/tweak.py
  test/framework/options.py
  test/framework/tweak.py
Labels: bug fix

#2829 update release notes for EasyBuild v3.9.0 release + bump version to 3.9.0
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2831 sync with master & bump version to 3.9.1dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2833 Lower required version in slurm job backend to 16.05
  easybuild/tools/job/slurm.py
  test/framework/parallelbuild.py
Labels: enhancement

#2834 only call 'scontrol release' when there's at least one job submitted
  easybuild/tools/job/slurm.py
Labels: bug fix

#2835 fix small bug in find_eb_script + various minor issues with tests (related to environment in which tests are run)
  easybuild/tools/filetools.py
  test/framework/easyconfig.py
  test/framework/options.py
  test/framework/toy_build.py
  test/framework/utilities.py
Labels: bug fix

#2836 drop requirement for setuptools as runtime dependency
  .travis.yml
  easybuild/__init__.py
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/tools.py
  easybuild/framework/easyconfig/tweak.py
  easybuild/toolchains/__init__.py
  easybuild/toolchains/clanggcc.py
  easybuild/toolchains/compiler/__init__.py
  easybuild/toolchains/craycce.py
  easybuild/toolchains/craygnu.py
  easybuild/toolchains/crayintel.py
  easybuild/toolchains/craypgi.py
  easybuild/toolchains/fft/__init__.py
  easybuild/toolchains/gcc.py
  easybuild/toolchains/gcccore.py
  easybuild/toolchains/gcccuda.py
  easybuild/toolchains/gnu.py
  easybuild/toolchains/iccifort.py
  easybuild/toolchains/linalg/__init__.py
  easybuild/toolchains/mpi/__init__.py
  easybuild/toolchains/pgi.py
  easybuild/tools/__init__.py
  easybuild/tools/deprecated/__init__.py
  easybuild/tools/docs.py
  easybuild/tools/include.py
  easybuild/tools/job/__init__.py
  easybuild/tools/module_naming_scheme/__init__.py
  easybuild/tools/module_naming_scheme/categorized_mns.py
  easybuild/tools/module_naming_scheme/easybuild_mns.py
  easybuild/tools/module_naming_scheme/hierarchical_mns.py
  easybuild/tools/module_naming_scheme/mns.py
  easybuild/tools/module_naming_scheme/toolchain.py
  easybuild/tools/module_naming_scheme/utilities.py
  easybuild/tools/modules.py
  easybuild/tools/package/__init__.py
  easybuild/tools/package/package_naming_scheme/__init__.py
  easybuild/tools/package/utilities.py
  easybuild/tools/repository/__init__.py
  easybuild/tools/toolchain/__init__.py
  easybuild/tools/toolchain/toolchain.py
  eb
  setup.py
  test/__init__.py
  test/framework/include.py
  test/framework/options.py
  test/framework/sandbox/easybuild/__init__.py
  test/framework/sandbox/easybuild/easyblocks/__init__.py
  test/framework/sandbox/easybuild/easyblocks/generic/__init__.py
  test/framework/sandbox/easybuild/tools/__init__.py
  test/framework/sandbox/easybuild/tools/module_naming_scheme/__init__.py
  test/framework/sandbox/easybuild/tools/module_naming_scheme/broken_module_naming_scheme.py
  test/framework/sandbox/easybuild/tools/module_naming_scheme/test_module_naming_scheme.py
  test/framework/sandbox/easybuild/tools/module_naming_scheme/test_module_naming_scheme_more.py
  test/framework/scripts.py
  test/framework/utilities.py
Labels: change

#2838 add function to determine whether specified easyblock is generic or not
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: enhancement

#2837 only import from pkg_resources (provided by setuptools) to check GC3Pie version
  .travis.yml
  easybuild/tools/job/gc3pie.py
  easybuild/tools/version.py
Labels: bug fix

#2839 list build dependencies *before* runtime dependencies, so dependencies listed via multi_deps are loaded first in toolchain environment
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: bug fix, change

#2844 add support to apply_regex_substitutions function to skip creation of backup
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: enhancement

#2842 allow setting parallel to 0 or False to disable adding the -j argument
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: bug fix

#2848 append to existing .modulerc file rather than overwriting it (if --force is used)
  easybuild/tools/module_generator.py
  test/framework/module_generator.py
Labels: bug fix

#2847 Be more careful when using single quotes for Tcl syntax
  .travis.yml
  easybuild/tools/module_generator.py
  easybuild/tools/utilities.py
  test/framework/module_generator.py
Labels: bug fix
