Repository easybuilders/easybuild-framework, pull requests merged in 2019-06, with the labels that each got.

#2905 Preserve interpreter options when fixing script shebang
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#2906 Remove shebang options - Improve apply_regex_substitution log output
  easybuild/framework/easyblock.py
  easybuild/tools/filetools.py
  test/framework/toy_build.py
Labels: bug fix, enhancement

#2907 install default set of OS packages in container recipes starting from scratch + allow customizing EasyBuild installation commands + 'post' commands
  easybuild/tools/containers/singularity.py
  test/framework/containers.py
Labels: containers

#2909 drop --container-base-image configuration option + rename --container-base-config to --container-config
  easybuild/tools/config.py
  easybuild/tools/containers/base.py
  easybuild/tools/containers/docker.py
  easybuild/tools/containers/singularity.py
  easybuild/tools/options.py
  test/framework/containers.py
Labels: change, code cleanup

#2910 configure Lmod w.r.t. spider cache in generated Singularity container recipes + also install OS pkgs for OpenSSL & IB libs
  easybuild/tools/containers/singularity.py
Labels: containers, enhancement

#2913 configure EasyBuild via environment variables, also consider /tmp/easybuild/sources in source path + add zip to set of default OS pkgs
  easybuild/tools/containers/singularity.py
Labels: change, enhancement

#2915 add support to pass additional arguments/options to 'eb' command in generated container recipe
  easybuild/tools/containers/singularity.py
  test/framework/containers.py
Labels: containers, enhancement

#2914 fix crash on iterated installation when using Cray toolchains
  easybuild/toolchains/linalg/libsci.py
  test/framework/toolchain.py
Labels: bug fix

#2918 disable checking of read/exec permissions when checking for availability of 'sudo' command
  easybuild/tools/containers/utils.py
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix

#2919 update release notes & bump version for EasyBuild v3.9.2 release
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2920 release EasyBuild v3.9.2
  .travis.yml
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/scripts/bootstrap_eb.py
  easybuild/toolchains/linalg/libsci.py
  easybuild/tools/config.py
  easybuild/tools/containers/base.py
  easybuild/tools/containers/docker.py
  easybuild/tools/containers/singularity.py
  easybuild/tools/containers/utils.py
  easybuild/tools/filetools.py
  easybuild/tools/options.py
  easybuild/tools/version.py
  test/framework/containers.py
  test/framework/filetools.py
  test/framework/toolchain.py
  test/framework/toy_build.py
Labels: update

#2922 sync with master + bump version to 3.9.3dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2928 stick to Ubuntu Trusty when testing with Python 2.6 in Travis
  .travis.yml
Labels: bug fix

#2932 also consider 'python3' in 'eb' script
  .travis.yml
  eb
Labels: enhancement

#2937 honor --tmp-logdir when determining location of temporary log file
  easybuild/tools/build_log.py
  easybuild/tools/options.py
  test/framework/config.py
  test/framework/run.py
Labels: bug fix
