Repository easybuilders/easybuild-framework, pull requests merged in 2019-03, with the labels that each got.

#2791 fix UnicodeDecodeError on command output using 'replace' mode in run_cmd & run_cmd_qa
  easybuild/tools/run.py
  test/framework/run.py
Labels: bug fix, python3

#2792 avoid TypeError when checking gompi/iccifort/iimpi/intel versions for deprecation
  easybuild/toolchains/gompi.py
  easybuild/toolchains/iccifort.py
  easybuild/toolchains/iimpi.py
  easybuild/toolchains/intel.py
Labels: bug fix, python3

#2793 Add parameters for pretestopts and testopts.
  easybuild/framework/easyconfig/default.py
Labels: enhancement

#2794 take into account possible 'system' version when checking toolchain versions for deprecation
  easybuild/toolchains/gompi.py
  easybuild/toolchains/iccifort.py
  easybuild/toolchains/iimpi.py
  easybuild/toolchains/intel.py
Labels: python3

#2796 Use pid in backup name candidate to reduce risk of two processes colliding.
  easybuild/tools/filetools.py
  test/framework/filetools.py
  test/framework/options.py
  test/framework/toy_build.py
Labels: bug fix, enhancement

#2799 automatically enable --ignore-osdeps when using --preview-pr
  easybuild/tools/config.py
Labels: enhancement

#2800 fix test_import_available_modules on top of Python 3.7 by making sure sys.path has an empty entry
  .travis.yml
  test/framework/general.py
Labels: bug fix, python3

#2801 fix UnicodeEncodeError raised from run_cmd with Python 2.7
  easybuild/tools/run.py
  test/framework/run.py
Labels: bug fix, python3

#2802 enable silent mode for --new-pr and --update-pr
  easybuild/tools/github.py
  easybuild/tools/options.py
Labels: bug fix

#2804 avoid relying on order in which keys are processed in to_dependency
  easybuild/framework/easyconfig/types.py
Labels: bug fix

#2805 fix broken tests with Python 3.x + also test with Python 3.5
  .travis.yml
  easybuild/base/generaloption.py
  easybuild/base/rest.py
  easybuild/base/testing.py
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/format/format.py
  easybuild/framework/easyconfig/format/one.py
  easybuild/framework/easyconfig/types.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  test/framework/run.py
Labels: python3

#2806 ensure correct value type in data field of Request object in Python 2/3
  easybuild/base/rest.py
  test/framework/github.py
Labels: bug fix, python3

#2807 update Travis config to reflect that PyYAML 5.x is no longer compatible with Python 2.6
  .travis.yml
Labels: bug fix

#2741 Make builddependencies iterable.
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/one.py
  easybuild/framework/easyconfig/tweak.py
  test/framework/easyconfig.py
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-iter.eb
  test/framework/toy_build.py
Labels: enhancement

#2809 Fix yeb format to work with PyYaml 5
  .travis.yml
  easybuild/framework/easyconfig/format/yeb.py
  test/framework/yeb.py
Labels: bug fix

#2810 fix problem with list of iterative easyconfig parameters being determined too early + reset toolchain variables on iterations
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/tools/toolchain/toolchain.py
Labels: bug fix

#2811 add tests for bugs fixed in #2810
  test/framework/sandbox/easybuild/easyblocks/t/toy.py
  test/framework/toolchain.py
Labels: bug fix

#2812 take into account that builddependencies is always a list in EasyBlock.det_iter_cnt
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: bug fix

#2819 iterate over subdirectories in order in find_egg_dir_for of bootstrap script, to ensure oldest vsc-install is picked
  .travis.yml
  easybuild/scripts/bootstrap_eb.py
Labels: bug fix

#2817 fix typo in error message for use of unknown easyconfig parameter
  easybuild/framework/easyconfig/default.py
  test/framework/easyconfig.py
Labels: bug fix

#2818 enhance log_file_format to fix problem when %(name)s template value is used for log directory
  easybuild/framework/easyblock.py
  easybuild/tools/config.py
  easybuild/tools/package/utilities.py
  test/framework/config.py
Labels: bug fix

#2821 replace -Wl,--enable-new-dtags compiler option with -Wl,--disable-new-dtags in RPATH wrapper script
  easybuild/scripts/rpath_args.py
  test/framework/toolchain.py
Labels: bug fix

#2823 Updated COMPILER_F77 for PGI >= 19.1
  easybuild/toolchains/compiler/pgi.py
  test/framework/toolchain.py
Labels: bug fix, update

#2813 add support for multi_deps easyconfig parameter (syntactic sugar for iterative list of builddependencies)
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/format.py
  easybuild/framework/easyconfig/format/one.py
  easybuild/framework/easyconfig/templates.py
  easybuild/framework/extensioneasyblock.py
  easybuild/tools/hooks.py
  test/framework/easyconfig.py
Labels: enhancement
