Repository easybuilders/easybuild-framework, pull requests merged in 2019-11, with the labels that each got.

#3069 imply --disable-pre-create-installdir with --inject-checksums
  easybuild/tools/options.py
  test/framework/options.py
Labels: bug fix

#3071 skip validation when copying EasyConfig object for extension
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/extension.py
  test/framework/easyconfig.py
Labels: bug fix

#3055 correctly handle iccifortcuda toolchain with standalone iccifort in det_toolchain_compilers
  easybuild/tools/module_naming_scheme/toolchain.py
  test/framework/modules.py
  test/framework/modules/CUDA/9.1.85
  test/framework/modules/iccifort/2019.5.281
  test/framework/modules/iccifortcuda/2018b
  test/framework/modules/iccifortcuda/2019a
  test/framework/toolchain.py
Labels: bug fix

#3073 correctly specify that ActiveMNS & co are singleton classes
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/tools/module_naming_scheme/mns.py
  easybuild/tools/package/utilities.py
  test/framework/easyconfig.py
Labels: bug fix, python3

#3074 don't call out to prohibitively expensive getRootLoggerName in getLogger, just use 'root' instead
  easybuild/base/fancylogger.py
  test/framework/build_log.py
Labels: change, performance

#3067 Handle patches in extensions more like normal patches.
  easybuild/framework/easyblock.py
  easybuild/framework/extensioneasyblock.py
  test/framework/easyconfig.py
  test/framework/toy_build.py
Labels: bug fix, enhancement

#3047 add support for specifying different dependency version based on architecture
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: enhancement

#3078 take into account that platform.linux_distribution and platform.dist was removed in Python 3.8
  .github/workflows/unit_tests.yml
  .travis.yml
  easybuild/tools/systemtools.py
Labels: bug fix, python3

#3075 support use of glob patterns for paths to files with external modules metadata
  easybuild/tools/options.py
  test/framework/options.py
Labels: enhancement

#3077 deprecate support for using Lmod 6.x
  .github/workflows/unit_tests.yml
  .travis.yml
  easybuild/tools/config.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  test/framework/modulestool.py
  test/framework/utilities.py
Labels: change

#3076 deprecate running EasyBuild with Python 2.6 via new check_python_version() function
  .travis.yml
  easybuild/tools/options.py
  easybuild/tools/systemtools.py
  test/framework/systemtools.py
Labels: change

#3081 always include mandatory easyconfig parameters in dumped easyconfig
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/one.py
  test/framework/easyconfig.py
Labels: bug fix

#3083 take into account that external modules may not be visible directly (due to module hierarchy)
  easybuild/framework/easyconfig/tools.py
  easybuild/tools/options.py
  easybuild/tools/toolchain/toolchain.py
  test/framework/options.py
  test/framework/toy_build.py
Labels: enhancement

#3086 trim set of test configurations in Travis CI
  .travis.yml
Labels: change

#3088 flesh out env_vars_external_module from Toolchain._simulated_load_dependency_module
  easybuild/tools/toolchain/toolchain.py
  test/framework/toolchain.py
Labels: change

#3087 add support for --sync-pr-with-develop
  easybuild/main.py
  easybuild/tools/github.py
  easybuild/tools/options.py
  test/framework/github.py
  test/framework/options.py
Labels: enhancement

#3089 hide backup module file when using Lmod 6.x (fixes #9302)
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#3092 add better error message when mandatory key is missing from a dictionary easyconfig parameter
  easybuild/framework/easyconfig/format/one.py
Labels: bug fix

#3093 also create symlinks for default modules in class module folders
  easybuild/framework/easyblock.py
  easybuild/tools/module_generator.py
  test/framework/options.py
Labels: bug fix

#3094 fix semantics of --set-default-module: only set default for specified easyconfigs, not for the ones that are installed as dependencies via --robot
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/main.py
  test/framework/options.py
Labels: bug fix

#3096 don't use %(version)s template in exts_default_options in dumped easyconfig
  easybuild/framework/easyconfig/format/format.py
  test/framework/easyconfig.py
Labels: bug fix

#3095 fix various issues in extracting comments from original easyconfig file and including them again in dumped easyconfig
  easybuild/framework/easyconfig/format/one.py
  test/framework/easyconfig.py
Labels: bug fix

#3097 fix generated module statements in case only a single version is listed in multi_deps
  easybuild/tools/module_generator.py
  test/framework/module_generator.py
Labels: bug fix

#3099 Fix inconsistent module path usage that leads to repeated reloading in HMNS
  easybuild/tools/modules.py
  test/framework/modules.py
Labels: bug fix

#3105 fix broken test_show_system_info on macOS due to 'Python' binary
  test/framework/options.py
Labels: bug fix

#3085 adds support for including 'extensions' statement in Lua modules with Lmod 8.2+
  easybuild/tools/module_generator.py
  test/framework/module_generator.py
Labels: enhancement

#3103 add support for --new-branch-github, --new-pr-from-branch, --sync-branch-with-develop, --update-branch-github
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/main.py
  easybuild/tools/config.py
  easybuild/tools/github.py
  easybuild/tools/options.py
  test/framework/options.py
Labels: enhancement

#3106 fix typo in docstring for new_branch_github
  easybuild/tools/github.py
Labels: bug fix

#3107 make including 'extensions' statement in generated Lua module files opt-in for now
  easybuild/tools/config.py
  easybuild/tools/module_generator.py
  easybuild/tools/options.py
  test/framework/module_generator.py
Labels: bug fix, change

#3108 sync develop with 4.1.x release branch
  easybuild/tools/config.py
  easybuild/tools/github.py
  easybuild/tools/module_generator.py
  easybuild/tools/options.py
  test/framework/module_generator.py
Labels: bug fix
