Repository easybuilders/easybuild-framework, pull requests merged in 2019-01, with the labels that each got.

#2710 avoid '+' in directory name for g++ rpath wrapper
  easybuild/tools/toolchain/toolchain.py
  test/framework/toolchain.py
Labels: bug fix

#2711 replace 'except IOError, err:' pattern with 'except IOError as err:' for compatibility with Python 3.x
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/format.py
  easybuild/framework/easyconfig/format/pyheaderconfigobj.py
  easybuild/framework/easyconfig/format/version.py
  easybuild/framework/easyconfig/parser.py
  easybuild/framework/easyconfig/tools.py
  easybuild/framework/easyconfig/tweak.py
  easybuild/main.py
  easybuild/scripts/add_header.py
  easybuild/scripts/fix_broken_easyconfigs.py
  easybuild/scripts/generate_software_list.py
  easybuild/scripts/mk_tmpl_easyblock_for.py
  easybuild/scripts/port_easyblock.py
  easybuild/scripts/prep_for_release.py
  easybuild/scripts/repo_setup.py
  easybuild/tools/asyncprocess.py
  easybuild/tools/configobj.py
  easybuild/tools/convert.py
  easybuild/tools/environment.py
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  easybuild/tools/jenkins.py
  easybuild/tools/job/pbs_python.py
  easybuild/tools/module_generator.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  easybuild/tools/parallelbuild.py
  easybuild/tools/repository/gitrepo.py
  easybuild/tools/repository/hgrepo.py
  easybuild/tools/repository/repository.py
  easybuild/tools/repository/svnrepo.py
  easybuild/tools/run.py
  easybuild/tools/systemtools.py
  easybuild/tools/testing.py
Labels: code cleanup

#2713 move mk_rst_table function from easybuild.tools.docs to easybuild.tools.utilities
  easybuild/base/generaloption.py
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/format/format.py
  easybuild/framework/easyconfig/format/one.py
  easybuild/framework/easyconfig/format/yeb.py
  easybuild/tools/docs.py
  easybuild/tools/utilities.py
Labels: change

#2716 avoid use of sys.maxint in dependencies_for
  easybuild/tools/module_generator.py
  test/framework/module_generator.py
Labels: code cleanup, python3

#2715 make all print statements compatible with Python 3
  easybuild/framework/easyconfig/tools.py
  easybuild/main.py
  easybuild/scripts/add_header.py
  easybuild/scripts/fix_docs.py
  easybuild/scripts/mk_tmpl_easyblock_for.py
  easybuild/scripts/prep_for_release.py
  easybuild/tools/github.py
  easybuild/tools/jenkins.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  easybuild/tools/robot.py
  test/framework/robot.py
Labels: code cleanup, python3

#2714 start testing with Python 3.6, add easybuild.tools.py2vs3 module, fix import for easybuild.base.* modules
  .travis.yml
  easybuild/base/fancylogger.py
  easybuild/base/generaloption.py
  easybuild/base/optcomplete.py
  easybuild/base/rest.py
  easybuild/base/testing.py
  easybuild/tools/py2vs3/__init__.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  easybuild/tools/utilities.py
  setup.py
  test/python3_testing.sh
Labels: python3

#2717 pre-install vsc-install < 0.11.4 to avoid requiring mock Python package
  .travis.yml
  easybuild/scripts/bootstrap_eb.py
Labels: bug fix

#2719 fix import with Python 3 for easybuild.tools.* modules and easybuild.main
  easybuild/base/fancylogger.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/tools.py
  easybuild/framework/easyconfig/types.py
  easybuild/main.py
  easybuild/tools/build_details.py
  easybuild/tools/docs.py
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  easybuild/tools/options.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  test/framework/filetools.py
  test/python3_testing.sh
Labels: python3

#2703 Speedup check os dependency
  easybuild/tools/systemtools.py
Labels: performance

#2720 fix check_pr_eligible_to_merge to only consider the status of the last test report
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#2721 consistently use 'string_type' from easybuild.tools.py2vs3 rather than 'basestring'
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/format.py
  easybuild/framework/easyconfig/format/one.py
  easybuild/framework/easyconfig/format/version.py
  easybuild/framework/easyconfig/format/yeb.py
  easybuild/framework/easyconfig/parser.py
  easybuild/framework/easyconfig/style.py
  easybuild/framework/easyconfig/templates.py
  easybuild/tools/config.py
  easybuild/tools/configobj.py
  easybuild/tools/containers/singularity.py
  easybuild/tools/containers/utils.py
  easybuild/tools/convert.py
  easybuild/tools/filetools.py
  easybuild/tools/module_generator.py
  easybuild/tools/module_naming_scheme/utilities.py
  easybuild/tools/options.py
  easybuild/tools/repository/repository.py
  easybuild/tools/run.py
  easybuild/tools/toolchain/compiler.py
  easybuild/tools/toolchain/options.py
  test/framework/easyconfigparser.py
  test/framework/license.py
  test/framework/systemtools.py
  test/framework/toolchain.py
  test/framework/toy_build.py
  test/framework/type_checking.py
  test/python3_testing.sh
Labels: python3

#2722 add support for 'eb --show-system-info'
  easybuild/tools/options.py
  test/framework/options.py
Labels: enhancement

#2723 fix running of set_up_configuration() in Python 3
  easybuild/base/generaloption.py
  easybuild/tools/build_log.py
  easybuild/tools/config.py
  easybuild/tools/configobj.py
  easybuild/tools/options.py
  easybuild/tools/py2vs3/__init__.py
  easybuild/tools/run.py
  test/framework/config.py
  test/python3_testing.sh
Labels: python3

#2725 filter (CUDA) lib*/stubs paths in RPATH wrapper script
  easybuild/scripts/rpath_args.py
  easybuild/tools/toolchain/toolchain.py
  test/framework/toolchain.py
Labels: bug fix

#2724 don't recreate build directory when buildininstalldir is enabled for iterative installations
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: bug fix

#2728 add support for %(arch)s template value in easyconfig files (x86-64, aarch64, ppc64le, ...)
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
Labels: enhancement

#2729 make filetools tests pass with Python 3
  easybuild/base/generaloption.py
  easybuild/tools/filetools.py
  easybuild/tools/modules.py
  easybuild/tools/multidiff.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  easybuild/tools/run.py
  test/framework/filetools.py
  test/framework/sandbox/easybuild/easyblocks/__init__.py
  test/framework/utilities.py
  test/python3_testing.sh
Labels: python3

#2737 update release notes + bump version for EasyBuild v3.8.1
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2739 bump version to 3.9.0dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2743 make tests for easybuild.tools.modules pass with Python 3
  easybuild/tools/modules.py
  test/framework/modules.py
  test/python3_testing.sh
Labels: python3
