Repository easybuilders/easybuild-framework, pull requests merged in 2019-05, with the labels that each got.

#2850 add support for %(pymajver)s (& co)
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
Labels: enhancement

#2852 correctly resolve template values used for extensions
  easybuild/framework/easyblock.py
  easybuild/framework/extension.py
  test/framework/easyconfig.py
Labels: bug fix

#2854 update template values after updating iterative easyconfig parameters
  easybuild/framework/easyblock.py
  test/framework/easyconfig.py
Labels: bug fix

#2849 Add Lmod 8 to test suite
  .travis.yml
  easybuild/tools/modules.py
Labels: enhancement

#2857 add top-level directories of hierarchical module naming scheme to $MODULEPATH before loading dependencies
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: bug fix

#2856 deprecate useless 'skip_lower' named argument in template_constant_dict, always define *lower templates
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/templates.py
  easybuild/tools/docs.py
  test/framework/easyconfig.py
Labels: bug fix

#2861 inject dependencies specified via multi_deps before normal build dependencies
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: bug fix, change

#2863 include Python version(s) in PR titles auto-generated by --new-pr
  easybuild/tools/github.py
  test/framework/options.py
Labels: enhancement

#2874 pip install -r requirements.txt
  .travis.yml
  requirements.txt
Labels: change, code cleanup, enhancement

#2875 setup.py: Update the PyPI trove classifiers
  setup.py
Labels: bug fix, update

#2876 fix Python classifiers in setup.py, should be (only) Python 2.6 & 2.7
  setup.py
Labels: bug fix

#2878 add support for 'fix_python_shebang_for' and 'fix_perl_shebang_for' easyconfig parameters
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  test/framework/toy_build.py
Labels: enhancement

#2870 Update HierarchicalMNS for GCCcore toolchain
  easybuild/tools/module_naming_scheme/hierarchical_mns.py
Labels: bug fix

#2880 make sure each Python version is only listed once in generated PR title
  easybuild/tools/github.py
  test/framework/options.py
Labels: bug fix

#2883 add support for 'eb --missing' ('eb -M')
  easybuild/main.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  easybuild/tools/robot.py
  test/framework/options.py
Labels: enhancement

#2882 Add multi_deps information to generated module, help and whatis sections.
  easybuild/tools/module_generator.py
  test/framework/toy_build.py
Labels: enhancement

#2886 bump iteration index counter at the correct time
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: bug report

#2887 don't specify --ntasks-per-node when submitting Slurm jobs
  easybuild/tools/job/slurm.py
  test/framework/parallelbuild.py
Labels: change

#2888 fix order of easyconfig parameters in output generated by 'eb --avail-easyconfig-params --output-format rst'
  easybuild/tools/docs.py
  test/framework/options.py
Labels: bug fix

#2889 update release notes & bump version for EasyBuild v3.9.1 release
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2890 release EasyBuild v3.9.1
  .travis.yml
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/templates.py
  easybuild/framework/extension.py
  easybuild/main.py
  easybuild/tools/config.py
  easybuild/tools/docs.py
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  easybuild/tools/job/slurm.py
  easybuild/tools/module_generator.py
  easybuild/tools/module_naming_scheme/hierarchical_mns.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  easybuild/tools/robot.py
  easybuild/tools/utilities.py
  easybuild/tools/version.py
  setup.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/filetools.py
  test/framework/module_generator.py
  test/framework/options.py
  test/framework/parallelbuild.py
  test/framework/toy_build.py
  test/framework/utilities.py
Labels: update

#2891 sync with master + bump version to 3.9.2dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2892 stick to vsc-base<2.9.0 in bootstrap script to avoid requiring 'future' dependency
  .travis.yml
  easybuild/scripts/bootstrap_eb.py
Labels: change, enhancement

#2895 fix parsing of easyconfig file that uses local variable in list comprehension when using Python 3.x
  easybuild/framework/easyconfig/format/pyheaderconfigobj.py
  test/framework/easyconfig.py
Labels: bug fix, python3

#2898 make --fix-deprecated-easyconfigs a bit less strict
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: bug fix

#2897 remove old scripts that are no longer useful (+ minor fixes to others)
  easybuild/scripts/EasyBuild-reinstall-dev.sh
  easybuild/scripts/add_header.py
  easybuild/scripts/generate_software_list.py
  easybuild/scripts/mk_tmpl_easyblock_for.py
  easybuild/scripts/port_easyblock.py
  easybuild/scripts/prep_for_release.py
  easybuild/scripts/repo_setup.py
  easybuild/scripts/run_easybuild_regtest.sh
  test/framework/scripts.py
  test/framework/suite.py
Labels: change, code cleanup

#2884 add support for --container-base-config and --container-template-recipe + rename --container-base to --container-base-image
  easybuild/tools/config.py
  easybuild/tools/containers/base.py
  easybuild/tools/containers/docker.py
  easybuild/tools/containers/singularity.py
  easybuild/tools/options.py
  test/framework/containers.py
Labels: change, enhancement

#2900 strip off leading/trailing whitespace from generated container recipes
  easybuild/tools/containers/base.py
  test/framework/containers.py
Labels: enhancement

#2902 add support for 'sif' container image format (only supported with Singularity 3.x)
  easybuild/tools/config.py
  easybuild/tools/containers/singularity.py
  test/framework/containers.py
Labels: containers, enhancement

#2899 make sure that easyconfig file for EasyBuild version being bootstrapped is found in robot search path
  .travis.yml
  easybuild/scripts/bootstrap_eb.py
Labels: bug fix

#2903 add support for specifying non-image based bootstrap agents in Singularity container recipes via --container-base-config
  easybuild/tools/containers/singularity.py
  test/framework/containers.py
Labels: containers, enhancement
