Repository easybuilders/easybuild-framework, pull requests merged in 2019-08, with the labels that each got.

#2951 deprecate toolchains older than gompi/2016a and foss/2016a
  easybuild/toolchains/foss.py
  easybuild/toolchains/gompi.py
  test/framework/options.py
  test/framework/robot.py
Labels: change

#2963 ensure 'docurls' easyconfig parameter value is a list of string values, not a single string value
  easybuild/framework/easyconfig/types.py
  test/framework/type_checking.py
Labels: enhancement

#2965 automatically enable --ignore-osdeps when using --check-contrib or --check-style
  easybuild/tools/config.py
Labels: enhancement

#2946 add support for specifying checksum via dict providing a filename-to-checksum mapping
  easybuild/framework/easyconfig/types.py
  easybuild/tools/filetools.py
  test/framework/filetools.py
  test/framework/type_checking.py
Labels: enhancement

#2958 add support for specifying tuple of alternative checksums
  easybuild/tools/filetools.py
  test/framework/filetools.py
  test/framework/type_checking.py
Labels: enhancement

#2956 enhance 'completed' message with how much time was needed the installation
  easybuild/framework/easyblock.py
  easybuild/tools/utilities.py
  test/framework/easyblock.py
  test/framework/options.py
  test/framework/toy_build.py
Labels: enhancement

#2960 support using 'system' as alias for 'dummy' toolchain
  easybuild/framework/easyconfig/constants.py
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfigparser.py
  test/framework/toy_build.py
Labels: enhancement

#2969 also consider extension patches when determining for which easyconfig a given patch file is intended in --new-pr/--update-pr
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#2968 replace --strict-local-var-naming with the more flexible --local-var-naming-check={error,log,warn}
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/easyconfig.py
  test/framework/utilities.py
Labels: change, enhancement

#2967 escape '+' in search queries + handle invalid search queries better
  easybuild/tools/filetools.py
  test/framework/filetools.py
  test/framework/options.py
Labels: bug fix

#2970 unset $CDPATH early on if it is defined (fixes #2944)
  easybuild/main.py
Labels: bug fix

#2972 create specified temporary log directory if it doesn't exist yet in init_logging
  easybuild/tools/build_log.py
  test/framework/build_log.py
  test/framework/options.py
Labels: bug fix

#2973 don't indicate first multi_deps version as default in module help text when multi_deps_load_default=False
  easybuild/tools/module_generator.py
  test/framework/toy_build.py
Labels: bug fix

#2977 update release notes + bump version for EasyBuild v3.9.4
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#2978 release EasyBuild v3.9.4
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/constants.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/types.py
  easybuild/main.py
  easybuild/toolchains/foss.py
  easybuild/toolchains/gompi.py
  easybuild/tools/build_log.py
  easybuild/tools/config.py
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  easybuild/tools/module_generator.py
  easybuild/tools/utilities.py
  easybuild/tools/version.py
  test/framework/build_log.py
  test/framework/easyblock.py
  test/framework/easyconfigparser.py
  test/framework/filetools.py
  test/framework/github.py
  test/framework/options.py
  test/framework/robot.py
  test/framework/toy_build.py
  test/framework/type_checking.py
Labels: update

#2982 make check for deprecated foss versions compatible with Python 3
  easybuild/toolchains/foss.py
Labels: bug fix, python3

#2979 use 'command -v' to avoid requiring 'which' in 'eb' command
  eb
Labels: change

#2984 include docs URL in warning/error about non-conforming names of local variables
  easybuild/framework/easyconfig/easyconfig.py
Labels: enhancement

#2988 stop trying to use setuptools.setup in setup.py, always use distutils.core.setup instead
  .travis.yml
  easybuild/tools/options.py
  setup.py
Labels: change
