Repository easybuilders/easybuild-framework, pull requests merged in 2019-02, with the labels that each got.

#2746 use assertEqual rather than assertEquals (which is deprecated)
  test/framework/easyconfig.py
  test/framework/github.py
  test/framework/run.py
  test/framework/toolchain.py
Labels: code cleanup

#2747 test with Tmod 4.1.4 (packaged in RHEL8) in Travis CI
  .travis.yml
Labels: change

#2752 fix argument name in close_pr
  easybuild/main.py
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#2751 fix variety of small issues to improve Python 3 compatibility
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/tools/configobj.py
  easybuild/tools/filetools.py
  easybuild/tools/toolchain/options.py
  easybuild/tools/toolchain/toolchain.py
  easybuild/tools/toolchain/utilities.py
  test/framework/filetools.py
  test/framework/toolchain.py
Labels: python3

#2748 Replace deps by hidden deps instead of removing them from the lists.
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/one.py
  test/framework/easyconfig.py
Labels: code cleanup

#2756 fix running of build_log/config/containers/docs tests with Python 3
  easybuild/base/frozendict.py
  easybuild/base/generaloption.py
  easybuild/framework/easyblock.py
  easybuild/tools/config.py
  easybuild/tools/configobj.py
  easybuild/tools/containers/utils.py
  easybuild/tools/docs.py
  easybuild/tools/github.py
  easybuild/tools/job/gc3pie.py
  easybuild/tools/job/pbs_python.py
  easybuild/tools/job/slurm.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  easybuild/tools/run.py
  easybuild/tools/toolchain/compiler.py
  test/framework/build_log.py
  test/framework/config.py
  test/python3_testing.sh
Labels: python3

#2757 fix undefined variable 'prefix' in Compiler._set_compiler_vars
  easybuild/tools/toolchain/compiler.py
Labels: bug fix

#2759 fix running systemtools test subsuite with Python 3 by using integer divsion in get_total_memory() function
  easybuild/tools/systemtools.py
  test/python3_testing.sh
Labels: python3

#2760 fix test account for GitHub-related tests
  test/framework/github.py
Labels: bug fix

#2761 fix running of github tests with Python 3
  easybuild/base/rest.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  test/framework/github.py
  test/python3_testing.sh
Labels: python3

#2762 fix running of toolchain tests with Python 3
  easybuild/framework/easyblock.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  test/python3_testing.sh
Labels: python3

#2763 make REST client actually return headers when http method is HEAD
  easybuild/base/rest.py
Labels: enhancement

#2765 fix running of 'asyncprocess' & 'run' test suite with Python 3
  easybuild/tools/asyncprocess.py
  easybuild/tools/run.py
  test/framework/asyncprocess.py
  test/python3_testing.sh
Labels: python3

#2766 fix running of 'easyconfig' test suite with Python 3
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/version.py
  easybuild/framework/easyconfig/style.py
  easybuild/framework/easyconfig/tweak.py
  easybuild/tools/utilities.py
  test/framework/easyconfig.py
  test/python3_testing.sh
Labels: python3

#2767 fix running of 'module_generator' test suite with Python 3
  easybuild/tools/module_generator.py
  test/framework/easyconfigs/test_ecs/i/iccifortcuda/iccifortcuda-2016.1.150.eb
  test/framework/easyconfigs/test_ecs/i/impi/impi-5.1.2.150-iccifortcuda-2016.1.150.eb
  test/framework/module_generator.py
  test/framework/robot.py
  test/framework/sandbox/easybuild/tools/module_naming_scheme/test_module_naming_scheme_more.py
  test/python3_testing.sh
Labels: python3

#2768 fix running of 'robot' test suite with Python 3
  easybuild/tools/modules.py
  test/python3_testing.sh
Labels: python3

#2772 make test for dep_graph function robust against changing order of lines in resulting dot file
  test/framework/easyconfig.py
Labels: bug fix

#2773 ensure non-zero exit code for all test subsuites (+ fix trivial style issues)
  test/framework/asyncprocess.py
  test/framework/build_log.py
  test/framework/config.py
  test/framework/containers.py
  test/framework/docs.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/easyconfigformat.py
  test/framework/easyconfigparser.py
  test/framework/easyconfigversion.py
  test/framework/ebconfigobj.py
  test/framework/environment.py
  test/framework/filetools.py
  test/framework/format_convert.py
  test/framework/general.py
  test/framework/github.py
  test/framework/hooks.py
  test/framework/include.py
  test/framework/lib.py
  test/framework/license.py
  test/framework/module_generator.py
  test/framework/modules.py
  test/framework/modulestool.py
  test/framework/options.py
  test/framework/package.py
  test/framework/parallelbuild.py
  test/framework/repository.py
  test/framework/robot.py
  test/framework/run.py
  test/framework/scripts.py
  test/framework/style.py
  test/framework/systemtools.py
  test/framework/toolchain.py
  test/framework/toolchainvariables.py
  test/framework/toy_build.py
  test/framework/tweak.py
  test/framework/type_checking.py
  test/framework/variables.py
  test/framework/yeb.py
Labels: bug fix, code cleanup

#2774 test all configuration with Python 3.6
  .travis.yml
Labels: python3

#2775 fix running of 'easyblock' test suite with Python 3
  easybuild/framework/easyblock.py
  easybuild/tools/version.py
  test/python3_testing.sh
Labels: python3

#2778 fix running of 'easyconfigparser' and 'format_convert' test suites with Python 3
  easybuild/base/wrapper.py
  easybuild/framework/easyconfig/format/convert.py
  easybuild/tools/convert.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  test/framework/format_convert.py
  test/python3_testing.sh
Labels: python3

#2780 fix running of 'options' test suite with Python 3
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/options.py
  test/python3_testing.sh
Labels: python3

#2781 silence printed deprecation warnings for easyconfigs/toolchains based on 'silent' build option
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/tools/build_log.py
  test/framework/build_log.py
Labels: enhancement

#2770 Make sure read permissions are always set.
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#2782 avoid printing of messages/warnings in framework test suite
  .travis.yml
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/tweak.py
  easybuild/toolchains/mpi/openmpi.py
  easybuild/tools/build_log.py
  easybuild/tools/filetools.py
  easybuild/tools/modules.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/github.py
  test/framework/lib.py
  test/framework/options.py
  test/framework/package.py
  test/framework/robot.py
  test/framework/suite.py
  test/framework/toolchain.py
  test/framework/toy_build.py
  test/framework/tweak.py
  test/framework/yeb.py
Labels: bug fix, code cleanup

#2785 fix running of 'toy_build' test suite with Python 3
  easybuild/framework/easyconfig/format/format.py
  easybuild/framework/easyconfig/format/version.py
  test/framework/easyconfigversion.py
  test/framework/toy_build.py
  test/python3_testing.sh
Labels: python3

#2786 fix problem with import_available_modules when running from easybuild-framework directory
  easybuild/tools/utilities.py
  test/framework/general.py
Labels: bug fix

#2787 fix running 'scripts' test subsuite with Python 3
  easybuild/scripts/fix_broken_easyconfigs.py
  easybuild/scripts/generate_software_list.py
  test/framework/scripts.py
  test/python3_testing.sh
Labels: python3

#2788 prepend location of test easyblocks to $PYTHONPATH to test_generate_software_list, rather than append
  test/framework/scripts.py
Labels: bug fix

#2789 fix last failing tests on top of Python 3 + run full test suite with Python 3
  .travis.yml
  easybuild/tools/hooks.py
  test/framework/easyconfigversion.py
  test/framework/hooks.py
  test/framework/options.py
  test/python3_testing.sh
Labels: python3

#2790 put fake 'vsc' namespace in place that produces an error on import
  easybuild/tools/filetools.py
  easybuild/tools/options.py
  test/framework/filetools.py
Labels: enhancement
