Repository easybuilders/easybuild-framework, pull requests merged in 2019-09, with the labels that each got.

#2931 Reverse lists for LDFLAGS and CPPFLAGS.
  easybuild/tools/variables.py
Labels: change

#2992 fix verbose output for 'eb' command, need to use "$@" to ensure arguments are shown correctly
  eb
Labels: bug fix

#2993 install fake 'vsc' namespace *before* parsing EasyBuild configuration
  easybuild/tools/filetools.py
  easybuild/tools/options.py
  test/framework/options.py
Labels: bug fix

#2983 Fixing a bug in which filtered dependencies based on complex filterin…
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfigs/test_ecs/f/foss/foss-2018a-broken.eb
  test/framework/easyconfigs/test_ecs/s/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2018a-OpenBLAS-0.2.20-broken.eb
  test/framework/options.py
Labels: bug fix

#2995 allow that icc & ifort are not actual dependencies in iccifort toolchain module
  easybuild/toolchains/iccifort.py
  test/framework/toolchain.py
Labels: change

#2996 HMNS: Define mapping for iccifort->intel for iccifort compiler-only.
  easybuild/tools/module_naming_scheme/hierarchical_mns.py
  easybuild/tools/module_naming_scheme/toolchain.py
  test/framework/easyconfigs/test_ecs/c/CUDA/CUDA-5.5.22-iccifort-2016.1.150.eb
  test/framework/easyconfigs/test_ecs/i/iccifort/iccifort-2016.1.150.eb
  test/framework/module_generator.py
Labels: bug fix, enhancement

#2695 Use requests instead of urllib2 for 403 errors.
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: enhancement

#2930 MKL: add -L$EBROOTIMKL/lib/intel64 to LDFLAGS
  easybuild/toolchains/linalg/intelmkl.py
Labels: enhancement

#3001 add back --add-dummy-to-minimal-toolchains as deprecated option
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/easyconfig.py
Labels: bug fix

#3003 add modluafooter & modtclfooter at the end of the generated module file
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#3006 print warning when 'eb' command is not found in $PATH and for empty robot search path
  easybuild/framework/easyconfig/tools.py
  easybuild/tools/options.py
Labels: change

#3007 change order of 'python*' commands considered by 'eb' command: python, python3, python2
  eb
Labels: change

#3008 fixes required to avoid breaking Cray support
  easybuild/framework/easyblock.py
  easybuild/tools/modules.py
  test/framework/easyblock.py
  test/framework/modules.py
Labels: bug fix, enhancement

#2999 Make installation independent of module naming scheme by default
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/options.py
  test/framework/toy_build.py
Labels: change

#2086 add check to ensure that --robot argument specifies an existing directory
  easybuild/tools/options.py
  test/framework/config.py
  test/framework/options.py
Labels: change

#3011 fix error reporting in adjust_permissions when using Python 3
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix

#3012 fixes for --read-only-installdir: avoid crash with ModuleRC easyblock + also make log file in installdir read-only
  easybuild/framework/easyblock.py
  test/framework/sandbox/easybuild/easyblocks/t/toy.py
  test/framework/toy_build.py
Labels: bug fix

#3013 update metadata for Cray-provided external modules
  etc/cray_external_modules_metadata.cfg
Labels: update

#3014 update release notes & bump version for EasyBuild v4.0.0 release
  RELEASE_NOTES
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/tools/version.py
Labels: update

#3016 drop reference to vsc-base from README
  README.rst
Labels: change

#3018 sync with master and bump version to 4.0.1dev
  README.rst
  RELEASE_NOTES
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/tools/version.py
Labels: update

#3019 fix broken test_download_repo due to archiving of easyconfigs
  test/framework/github.py
Labels: bug fix

#3023 sync develop with master after fixing broken test (cfr. #3019)
  test/framework/github.py
Labels: bug fix

#3017 update bootstrap script to support installing EasyBuild v4.0
  .travis.yml
  easybuild/scripts/bootstrap_eb.py
Labels: bug fix, update

#3029 enhance regex in fix_shebang method to fix more Python/Perl shebangs + avoid patching binary files
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#3031 delete test gist that is created by --check-github
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#3025 avoid that --inject-checksums introduces list of patches for extensions as a single long line (fixes #2734)
  easybuild/framework/easyblock.py
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-gompi-2018a-test.eb
  test/framework/options.py
  test/framework/sandbox/sources/toy/extensions/bar-0.0_fix-very-silly-typo-in-printf-statement.patch
Labels: bug fix

#3034 fix traceback with --inject-checksums for extensions that set a boolean easyconfig parameter
  easybuild/framework/easyblock.py
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-gompi-2018a-test.eb
  test/framework/options.py
Labels: bug fix

#3037 disable templates when defining easyconfig parameters in EasyConfig.set_keys()
  easybuild/framework/easyconfig/easyconfig.py
Labels: bug fix

#3036 add 'parallel' to list of config templates
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
Labels: enhancement

#3038 avoid setting GC3Pie's max_in_flight to None if --job-max-jobs is not specified
  easybuild/tools/job/gc3pie.py
  requirements.txt
Labels: bug fix, python3
