Repository easybuilders/easybuild-framework, pull requests merged in 2020-09, with the labels that each got.

#3382 add templates for CUDA compute capabilities
  easybuild/framework/easyconfig/default.py
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
Labels: enhancement

#3311 allow including easyblocks from multiple locations
  easybuild/tools/include.py
  easybuild/tools/options.py
  test/framework/include.py
  test/framework/options.py
Labels: bug fix

#3427 exclude local variables from typo check in easyconfig files
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: bug fix

#3426 make sure self.start_dir is set in ExtensionEasyBlock
  easybuild/framework/extensioneasyblock.py
Labels: enhancement

#3388 add EB option --generate-devel-module
  easybuild/framework/easyblock.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/modules.py
Labels: enhancement

#3435 determine start dir for extension from unpacked source directory of extension + enhance tests to capture bug
  easybuild/framework/extensioneasyblock.py
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-gompi-2018a-test.eb
  test/framework/options.py
  test/framework/sandbox/sources/toy/extensions/barbar-0.0.tar.gz
  test/framework/toy_build.py
Labels: bug fix

#3436 Exclude protobuf and pybind11 in createSubmoduleDeps
  easybuild/scripts/createSubmoduleDeps.sh
Labels: change

#3441 prepare release notes for EasyBuild v4.3.0
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3444 sync with master + bump version to 4.3.0dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3450 avoid UnicodeDecodeError in apply_regex_substitutions when patching files that include non-UTF-8 characters
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix, python3

#3428 consider $EB_INSTALLPYTHON to specify 'python' command to use for running EasyBuild
  eb
Labels: change

#3433 Further GCC toolchain fixes for aarch64.
  easybuild/toolchains/compiler/gcc.py
Labels: aarch64, enhancement

#3451 add path to pkg-config files in sysroot to $PKG_CONFIG_PATH when --sysroot is specified
  easybuild/tools/toolchain/toolchain.py
  test/framework/toolchain.py
Labels: enhancement
