Repository easybuilders/easybuild-framework, pull requests merged in 2020-03, with the labels that each got.

#3213 Allow use of SYSTEM as --try-toolchain option
  easybuild/tools/options.py
  test/framework/options.py
Labels: enhancement

#3226 fix broken test for --review-pr by using different PR to test with
  test/framework/options.py
Labels: bug fix

#3225 don't filter out None values in to_checksums, leave them in place
  easybuild/framework/easyconfig/types.py
  test/framework/type_checking.py
Labels: bug fix

#3234 use correct target account/repo when creating test report & posting comment in PR
  easybuild/tools/testing.py
Labels: bug fix

#3235 reorganize EasyBlock.extensions_step to ensure correct filtering of extensions
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
  test/framework/sandbox/easybuild/easyblocks/generic/dummyextension.py
Labels: bug fix

#3236 make --merge-pr take into account --pr-target-branch
  easybuild/tools/config.py
  easybuild/tools/github.py
  easybuild/tools/options.py
  test/framework/options.py
Labels: change, enhancement

#3237 First attempt at adding missing install/builddir templates to extensions.
  easybuild/framework/extension.py
  test/framework/easyconfig.py
Labels: bug fix

#3248 censor authorization part of headers before logging ReST API request
  RELEASE_NOTES
  easybuild/base/rest.py
  easybuild/tools/version.py
  requirements.txt
  test/framework/options.py
Labels: bug fix

#3249 sync develop with master after release of EasyBuild v4.1.2
  RELEASE_NOTES
  easybuild/base/rest.py
  easybuild/tools/version.py
  test/framework/options.py
Labels: bug fix, update

#3229 fix defining of $MPI_INC_* and $MPI_LIB_* environment variables for impi version 2019 and later
  easybuild/toolchains/mpi/intelmpi.py
Labels: bug fix

#3252 unset $GITHUB_TOKEN in Travis after installing token, to avoid failing test_from_pr_token_log
  .travis.yml
Labels: bug fix

#3244 make --check-contrib print a warning when None is used for checksums
  easybuild/framework/easyblock.py
  test/framework/options.py
Labels: enhancement

#3238 make tests use easybuilders/testrepository rather than hpcugent/testrepository after it was moved
  test/framework/filetools.py
  test/framework/github.py
  test/framework/repository.py
Labels: change

#2777 Add a contrib/hooks dir with some examples of hooks used.
  contrib/hooks/README.rst
  contrib/hooks/add_delete_configopt.py
  contrib/hooks/hpc2n_hooks.py
Labels: enhancement

#3228 Improve raised error in remove_dir and deprecate rmtree2
  easybuild/framework/easyblock.py
  easybuild/tools/containers/docker.py
  easybuild/tools/filetools.py
  easybuild/tools/repository/gitrepo.py
  easybuild/tools/repository/hgrepo.py
  easybuild/tools/repository/svnrepo.py
Labels: enhancement

#3254 Fix reporting when skipping extensions
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: bug fix

#3257 avoid API rate limit errors on online check in --check-github
  easybuild/tools/github.py
Labels: bug fix, change

#3258 Show EC names for parallel build
  easybuild/tools/parallelbuild.py
Labels: enhancement

#3227 mention CPU arch name in comment for uploaded test report, if it's known by archspec
  easybuild/tools/options.py
  easybuild/tools/systemtools.py
  easybuild/tools/testing.py
  requirements.txt
  test/framework/options.py
  test/framework/systemtools.py
Labels: enhancement

#3262 fix use of --copy-ec with a single argument, assume copy to current working directory
  easybuild/main.py
  test/framework/options.py
Labels: bug fix

#3009 adding locking to prevent two parallel builds of the same installation directory
  easybuild/framework/easyblock.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/toy_build.py
Labels: enhancement
