Repository easybuilders/easybuild-framework, pull requests merged in 2020-07, with the labels that each got.

#3375 Also put easyblocks used by extensions in `reprod` directory
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#3367 retain order of paths in when generating prepend_path statements for module file (don't sort them alphabetically)
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: bug fix

#3346 always take into account builddependencies when generating template values, also when we're not iteraring over builddependencies
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
Labels: bug fix, change

#3377 also copy template values in EasyConfig.copy method to ensure they are defined when installing extensions
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: bug fix

#3379 skip lines that start with 'module-version' when determining whether a module exists in ModulesTool.exist
  easybuild/tools/modules.py
  test/framework/modules.py
Labels: bug fix

#3381 prepare release notes for EasyBuild v4.2.2
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3383 release EasyBuild v4.2.2
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/templates.py
  easybuild/framework/easyconfig/tweak.py
  easybuild/tools/containers/singularity.py
  easybuild/tools/docs.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  easybuild/tools/version.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/modules.py
  test/framework/options.py
  test/framework/toy_build.py
  test/framework/tweak.py
Labels: update

#3384 sync develop with master + bump version to 4.2.3dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3392 cryptography: require 2.9.2 for Python 2.7
  requirements.txt
Labels: bug fix
