Repository easybuilders/easybuild-framework, pull requests merged in 2020-10, with the labels that each got.

#3452 avoid appending lib stubs pattern to RPATH filter over and over again
  easybuild/tools/toolchain/toolchain.py
Labels: bug fix

#3466 also remove empty checksums list specified in easyconfig file when using --inject-checksums
  easybuild/framework/easyblock.py
  test/framework/options.py
Labels: bug fix

#3464 Use only the sub folder name for createSubmoduleDeps script
  easybuild/scripts/createSubmoduleDeps.sh
Labels: change

#3446 take into account --include-easyblocks-from-pr when uploading test reports
  easybuild/main.py
  easybuild/tools/config.py
  easybuild/tools/testing.py
  test/framework/github.py
Labels: enhancement

#3465 fix compatibility with Python 3.9 by renaming fancy root logger
  .github/workflows/unit_tests.yml
  easybuild/base/fancylogger.py
  test/framework/build_log.py
Labels: bug fix

#3454 add support for NVHPC compiler + toolchain (based on PGI)
  easybuild/toolchains/compiler/nvhpc.py
  easybuild/toolchains/nvhpc.py
Labels: enhancement

#3474 don't raise error when Mpi.mpi_cmd_for fails for impi
  easybuild/tools/toolchain/mpi.py
  test/framework/toolchain.py
Labels: bug fix

#3477 unset $LD_LIBRARY_PATH when checking for OS dependencies with 'rpm' & co
  easybuild/tools/systemtools.py
  test/framework/systemtools.py
Labels: bug fix

#3480 allow including easyblocks from multiple PRs
  easybuild/tools/options.py
  test/framework/options.py
Labels: enhancement

#3460 Check for _VERSION and _PREFIX Cray environment variables with both software and module name
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: enhancement

#3481 take into account multiple easyblock PRs when uploading test reports
  easybuild/tools/options.py
  easybuild/tools/testing.py
Labels: enhancement

#3487 take source_urls, checksums, patches into account when extension source is specified via 'sources'
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#3486 don't change directory in download_repo function
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#3488 prepare release notes for EasyBuild v4.3.1
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: documentation, update

#3489 release EasyBuild v4.3.1
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/base/fancylogger.py
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/main.py
  easybuild/scripts/createSubmoduleDeps.sh
  easybuild/toolchains/compiler/gcc.py
  easybuild/toolchains/compiler/nvhpc.py
  easybuild/toolchains/nvhpc.py
  easybuild/tools/config.py
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  easybuild/tools/options.py
  easybuild/tools/systemtools.py
  easybuild/tools/testing.py
  easybuild/tools/toolchain/mpi.py
  easybuild/tools/toolchain/toolchain.py
  easybuild/tools/version.py
  eb
  test/framework/build_log.py
  test/framework/easyconfig.py
  test/framework/filetools.py
  test/framework/github.py
  test/framework/options.py
  test/framework/systemtools.py
  test/framework/toolchain.py
  test/framework/toy_build.py
Labels: update

#3492 sync with master + bump version to 4.3.2dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3491 also ignore vsc.* imports coming from from pkg_resources/__init__.py (setuptools) in fake vsc namespace
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix
