Repository easybuilders/easybuild-framework, pull requests merged in 2020-02, with the labels that each got.

#3192 increase timeout & use api.github.com for connectivity check in check_github
  easybuild/tools/github.py
Labels: bug fix, change

#3183 Fix shebang even if first line doesn't start with '#!'
  .gitignore
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#3168 also mention working directory + input passed via stdin (if any) in trace output of run_cmd
  easybuild/tools/run.py
  test/framework/run.py
  test/framework/toy_build.py
Labels: enhancement

#3194 fix online check in --check-github: try repeatedly and with different URLs to cater for HTTP issues
  easybuild/tools/github.py
Labels: bug fix

#3170 Fix EasyConfig.update code to handle both strings and lists as input.
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: bug fix

#3193 Restore flake8 default ignores
  setup.cfg
Labels: change

#3186 make boostrap script work with Python 3
  .github/workflows/unit_tests.yml
  .travis.yml
  easybuild/scripts/bootstrap_eb.py
Labels: bug fix

#3191 read patch files as bytestring to avoid UnicodeDecodeError for patches that include funky characters
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix

#3198 don't crash when GitPython is not installed in Python3
  easybuild/tools/version.py
Labels: bug fix, python3

#3201 Fix os_name_map for RHEL8.
  easybuild/tools/systemtools.py
Labels: bug fix, enhancement

#3197 Add an option to git_config to retain the .git directory
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: enhancement

#3176 Improve make_module_req
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
  test/framework/toy_build.py
Labels: enhancement

#3203 significantly speed up -D/--dry-run by avoiding useless 'module show'
  easybuild/framework/easyconfig/tools.py
Labels: bug fix, performance

#3119 Use correct module for errors_found_in_log
  easybuild/framework/easyblock.py
Labels: bug fix

#3208 don't add shebang to binary files
  easybuild/framework/easyblock.py
  easybuild/tools/filetools.py
  test/framework/filetools.py
  test/framework/toy_build.py
Labels: bug fix

#3204 enable tracking of test suite coverage using coveralls
  .coveragerc
  .travis.yml
Labels: change

#3212 Fix gitdb dependency on Python 2.6
  requirements.txt
Labels: bug fix

#3195 Optionally call log.warning in print_warning
  easybuild/tools/build_log.py
  test/framework/build_log.py
Labels: enhancement

#3219 use checkout@v2 in GitHub Actions to fix broken re-triggered tests
  .github/workflows/unit_tests.yml
Labels: bug fix
