Repository easybuilders/easybuild-framework, pull requests merged in 2020-05, with the labels that each got.

#3312 flesh out get_mpi_cmd_template function from Mpi.mpi_cmd_for method
  easybuild/tools/toolchain/mpi.py
  test/framework/toolchain.py
Labels: enhancement

#3316 print trace message for sanity check command before running it
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#3313 gitignore .mypy_cache dirs
  .gitignore
Labels: change

#3298 get pr_title and pr_descr built_options in new_pr_from_branch instead of new_pr (and commit_msg in both)
  easybuild/tools/github.py
  test/framework/options.py
Labels: bug fix

#3292 add 'change_into_dir' named argument to 'extract_file' + print deprecation warning if it's not specified
  easybuild/framework/easyblock.py
  easybuild/framework/extensioneasyblock.py
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  test/framework/easyblock.py
  test/framework/filetools.py
Labels: change

#3291 clean up locks when EasyBuild session is cancelled with signal like SIGTERM
  easybuild/framework/easyblock.py
  easybuild/main.py
  easybuild/tools/config.py
  easybuild/tools/filetools.py
  easybuild/tools/options.py
  test/framework/filetools.py
  test/framework/toy_build.py
Labels: enhancement

#3287 Introduce contextmanager for disabling templating and reduce resolving errors
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/extension.py
  easybuild/tools/module_generator.py
  test/framework/tweak.py
Labels: change

#3321 fix broken test_toy_lock_cleanup_signals & properly clean up after using SIGALRM signal in tests
  test/framework/run.py
  test/framework/toy_build.py
Labels: bug fix

#3320 make test_find_eb_script more robust in case $EB_SCRIPT_PATH is already set
  test/framework/filetools.py
Labels: bug fix

#3319 Fix problems with CrayCCE processing when there are no actual external modules
  easybuild/toolchains/mpi/craympich.py
  easybuild/tools/module_naming_scheme/hierarchical_mns.py
  easybuild/tools/toolchain/mpi.py
  test/framework/easyconfigs/test_ecs/h/HPL/HPL-2.1-CrayCCE-5.1.29.eb
  test/framework/filetools.py
  test/framework/module_generator.py
  test/framework/options.py
Labels: bug fix

#3314 Improve install_eb_dep.sh
  easybuild/scripts/install_eb_dep.sh
Labels: change, code cleanup

#3309 Constants for osdependecies.
  easybuild/framework/easyconfig/constants.py
  test/framework/easyconfigparser.py
Labels: enhancement

#3325 A couple of bug fixes with `tweak.py` for `--try-update-deps`
  easybuild/framework/easyconfig/tweak.py
Labels: bug fix

#3326 Only calculate the mapping of version suffixes if they are actually used
  easybuild/framework/easyconfig/tweak.py
  test/framework/tweak.py
Labels: bug fix

#3328 add --disable-job in 'eb' command used in jobs, to prevent infinite job cycle
  easybuild/tools/parallelbuild.py
  test/framework/parallelbuild.py
Labels: bug fix

#3329 make pypi_source_urls more robust by using HTMLParser rather than xml.etree.ElementTree
  easybuild/tools/filetools.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
Labels: bug fix, change

#3246 Adding sorting to rst output of list_toolchains to match txt and none
  easybuild/tools/docs.py
  test/framework/options.py
Labels: bug fix

#3330 check easyconfig itself as well as deps for versionsuffix when using --try-update-deps
  easybuild/framework/easyconfig/tweak.py
Labels: bug fix

#3333 avoid empty entries in $LD_LIBRARY_PATH and other path-like environment variables
  easybuild/tools/environment.py
  test/framework/environment.py
Labels: bug fix

#3334 Add OS_PKG_PAM_DEV constant for osdependencies
  easybuild/framework/easyconfig/constants.py
Labels: enhancement

#3337 reinstate fallback to ModulesTool.module_wrapper_exists in ModulesTool.exist
  easybuild/tools/modules.py
  test/framework/modules.py
Labels: bug fix

#3332 allow copying of tweaked easyconfigs when using --try-* with --copy-ec
  easybuild/main.py
  test/framework/options.py
Labels: enhancement

#3282 fix code style issues in easybuild.tools + add flake8 linting test
  .github/workflows/linting.yml
  easybuild/tools/asyncprocess.py
  easybuild/tools/configobj.py
  easybuild/tools/containers/utils.py
  easybuild/tools/docs.py
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  easybuild/tools/include.py
  easybuild/tools/job/gc3pie.py
  easybuild/tools/job/pbs_python.py
  easybuild/tools/module_generator.py
  easybuild/tools/module_naming_scheme/categorized_mns.py
  easybuild/tools/module_naming_scheme/migrate_from_eb_to_hmns.py
  easybuild/tools/module_naming_scheme/mns.py
  easybuild/tools/modules.py
  easybuild/tools/multidiff.py
  easybuild/tools/ordereddict.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  easybuild/tools/repository/hgrepo.py
  easybuild/tools/robot.py
  easybuild/tools/run.py
  easybuild/tools/systemtools.py
  easybuild/tools/toolchain/constants.py
  easybuild/tools/toolchain/linalg.py
  easybuild/tools/toolchain/mpi.py
  easybuild/tools/toolchain/toolchain.py
  easybuild/tools/toolchain/variables.py
  easybuild/tools/variables.py
Labels: code cleanup

#3339 bump version and update release notes for EasyBuild v4.2.1
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: documentation, update

#3343 sync develop with master + bump version to 4.2.2dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3344 add support for software minver template (like %(pyminver)s, etc.)
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
Labels: enhancement

#3347 fix running command as 'easybuild' user in generated Singularity definition file
  easybuild/tools/containers/singularity.py
Labels: bug fix
