Repository easybuilders/easybuild-framework, pull requests merged in 2020-01, with the labels that each got.

#3147 ensure subdirectories in software install directory have correct search (exec) permission
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#3151 mention --disable-* option in --help output for boolean options enabled by default
  easybuild/base/generaloption.py
  test/framework/options.py
Labels: enhancement

#3152 Only remove folders that contain no files recursively
  easybuild/framework/easyblock.py
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix

#3153 take into account that a checksum value may be a tuple of valid checksum in EasyBlock.check_checksums
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
Labels: bug fix

#3162 ignore "Black would make changes" produced by flake8-black
  setup.cfg
Labels: change

#3161 add --cuda-compute-capabilities configuration option
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/options.py
Labels: enhancement

#3129 Fix or avoid warnings that commonly arise in build log
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/extension.py
  easybuild/framework/extensioneasyblock.py
  easybuild/tools/build_log.py
  easybuild/tools/filetools.py
  easybuild/tools/modules.py
  easybuild/tools/systemtools.py
  easybuild/tools/toolchain/options.py
  test/framework/build_log.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/sandbox/sources/p/pi/dummy.tgz
Labels: bug fix

#3118 Add check_log_for_errors to detect and handle multiple errors
  easybuild/tools/run.py
  test/framework/run.py
Labels: enhancement

#3163 update release notes for EasyBuild v4.1.1
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3166 sync develop with master and bump version to 4.1.2dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update
