Repository easybuilders/easybuild-framework, pull requests merged in 2021-12, with the labels that each got.

#3906 fall back to sequential installation for extensions with unknown dependencies
  easybuild/framework/easyblock.py
  easybuild/framework/extension.py
  test/framework/toy_build.py
Labels: enhancement

#3908 make test_run_cmd_async more robust against fluke failures
  test/framework/run.py
Labels: bug fix

#3907 pick up custom extract_cmd specified for extension
  easybuild/framework/easyblock.py
  easybuild/framework/extension.py
  easybuild/framework/extensioneasyblock.py
  easybuild/tools/filetools.py
  test/framework/filetools.py
  test/framework/toy_build.py
Labels: bug fix

#3900 introduce EasyBlock.post_init method to correctly define builddir variable when build-in-installdir mode is enabled in easyconfig or easyblock
  easybuild/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/options.py
Labels: bug fix

#3909 allow oversubscription in sanity check for OpenMPI-based toolchains
  easybuild/framework/easyblock.py
Labels: enhancement

#3913 prepare release notes for EasyBuild v4.5.1 + bump version to 4.5.1
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3916 release EasyBuild v4.5.1
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/tools.py
  easybuild/framework/extension.py
  easybuild/framework/extensioneasyblock.py
  easybuild/main.py
  easybuild/tools/filetools.py
  easybuild/tools/options.py
  easybuild/tools/version.py
  test/framework/config.py
  test/framework/easyconfig.py
  test/framework/filetools.py
  test/framework/options.py
  test/framework/run.py
  test/framework/toy_build.py
Labels: update

#3917 sync with main + bump version to 4.5.2dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3919 automatically prepend env-for-shebang value with sysroot
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: enhancement, EESSI
