Repository easybuilders/easybuild-framework, pull requests merged in 2021-09, with the labels that each got.

#3795 make sure git clone with a tag argument actually downloads a tag
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix

#3808 add support for fix_bash_shebang_for
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  test/framework/toy_build.py
Labels: enhancement

#3805 Correctly resolve templates for patches in extensions when uploading to GitHub
  easybuild/tools/github.py
  test/framework/github.py
  test/framework/sandbox/easybuild/easyblocks/generic/pythonbundle.py
Labels: bug fix

#3816 pick up $MODULES_CMD to facilitate using Environment Modules 4.x as modules tool
  easybuild/tools/modules.py
Labels: enhancement

#3817 use more sensible branch name for creating easyblocks PR with --new-pr
  easybuild/tools/github.py
  test/framework/options.py
Labels: enhancement

#3819 prepare release notes for EasyBuild v4.4.2 + bump version to 4.4.2
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3821 sync with main + bump version to 4.4.3dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3823 Use Rich (if available) to show progress bar when installing easyconfigs
  easybuild/framework/easyblock.py
  easybuild/main.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  easybuild/tools/output.py
  requirements.txt
Labels: enhancement

#3826 expand progress bar to full screen width
  easybuild/tools/output.py
Labels: enhancement, change

#3829 add support for checking required/optional EasyBuild dependencies via 'eb --check-eb-deps'
  easybuild/main.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  easybuild/tools/output.py
  easybuild/tools/systemtools.py
  test/framework/options.py
Labels: enhancement

#3833 add --output-style configuration option, which can be used to disable use of Rich or type of any colored output
  easybuild/tools/config.py
  easybuild/tools/options.py
  easybuild/tools/output.py
  test/framework/output.py
  test/framework/suite.py
Labels: enhancement

#3832 ensure that path configuration options have absolute path values
  easybuild/tools/options.py
  test/framework/config.py
  test/framework/options.py
Labels: enhancement, bug fix

#3840 take into account changed error raised by Python 3.9.7 when copying directory via shutil.copyfile
  test/framework/filetools.py
Labels: bug fix

#3835 disable progress bars when running the tests to avoid messing up test suite output
  test/framework/output.py
  test/framework/utilities.py
Labels: bug fix

#3836 change copy_file function to raise an error when trying to copy non-existing file
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: enhancement, change

#3850 Ensure newer location of CUDA stubs is taken into account by RPATH filter
  easybuild/tools/toolchain/toolchain.py
  test/framework/toolchain.py
Labels: bug fix

#3851 add support for collecting GPU info (via nvidia-smi), and include it in --show-system-info and test report
  easybuild/tools/options.py
  easybuild/tools/systemtools.py
  easybuild/tools/testing.py
Labels: enhancement

#3855 fix copy_file so it doesn't fail when copying a symbolic link if the target path is an existing directory
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix
