Repository easybuilders/easybuild-framework, pull requests merged in 2021-02, with the labels that each got.

#3541 Add toolchain deps to template resolution
  easybuild/framework/easyconfig/templates.py
  test/framework/robot.py
Labels: enhancement

#3561 rename EasyBlock._skip_step to EasyBlock.skip_step, to make it part of the public API
  easybuild/framework/easyblock.py
Labels: change

#3560 avoid initializing Toolchain instance when taking into account toolchain dependencies for templates
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
  test/framework/robot.py
Labels: enhancement

#3570 Making symlinking of posix_c.so to posix.so in test suite configuration conditional
  .github/workflows/unit_tests.yml
Labels: bug fix, tests

#3566 Create the lib64 symlink as a relative symlink
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: change

#3571 Don't reuse variable name in the loop to fix adding extra compiler flags via toolchainopts
  easybuild/tools/toolchain/compiler.py
  test/framework/toolchain.py
Labels: bug fix

#3572 use http://sources/easybuild.io as fallback source URL
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: enhancement

#3553 Avoid no-op changes to $LD_* environment variables in ModulesTool
  easybuild/tools/modules.py
Labels: bug fix

#3574 add toolchain definition for iibff toolchain
  easybuild/toolchains/iibff.py
Labels: enhancement

#3576 use https for sources.easybuild.io fallback URL
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: change

#3578 Add cuda_cc_space_sep and cuda_cc_semicolon_sep templates
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
Labels: enhancement

#3472 add support for using customized HTTP headers in download_file
  easybuild/tools/build_log.py
  easybuild/tools/config.py
  easybuild/tools/filetools.py
  easybuild/tools/options.py
  test/framework/build_log.py
  test/framework/options.py
Labels: enhancement

#3565 Fix UTF-8 encoding errors when running EasyBuild with Python 3.0.x-3.6.x
  .github/workflows/unit_tests.yml
  easybuild/base/fancylogger.py
  easybuild/base/optcomplete.py
  easybuild/scripts/fix_docs.py
  easybuild/scripts/mk_tmpl_easyblock_for.py
  easybuild/tools/configobj.py
  easybuild/tools/environment.py
  easybuild/tools/filetools.py
  easybuild/tools/jenkins.py
  easybuild/tools/modules.py
  test/framework/build_log.py
  test/framework/easyblock.py
  test/framework/filetools.py
  test/framework/github.py
  test/framework/modules.py
  test/framework/modulestool.py
  test/framework/options.py
  test/framework/package.py
  test/framework/sandbox/easybuild/easyblocks/t/toy.py
  test/framework/utilities.py
Labels: bug fix

#3558 Allow use of alternate envvar(s) to $HOME for user modules
  easybuild/framework/easyblock.py
  easybuild/tools/config.py
  easybuild/tools/module_generator.py
  easybuild/tools/options.py
  test/framework/easyblock.py
  test/framework/module_generator.py
Labels: enhancement

#3580 symlink 'lib' to 'lib64' if it doesn't exist
  easybuild/framework/easyblock.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/toy_build.py
Labels: bug fix

#3581 add support for intel-compiler compiler toolchain (>= 2021.x versions, oneAPI)
  easybuild/toolchains/compiler/intel_compilers.py
  easybuild/toolchains/intel-compilers.py
Labels: enhancement

#3582 fix Python module filename for intel-compilers toolchain
  easybuild/toolchains/intel_compilers.py
Labels: bug fix

#3177 advise PR labels in --review-pr and add support for --add-pr-labels
  easybuild/framework/easyconfig/tools.py
  easybuild/main.py
  easybuild/tools/github.py
  easybuild/tools/options.py
  test/framework/github.py
  test/framework/options.py
  test/framework/sandbox/easybuild/easyblocks/e/__init__.py
  test/framework/sandbox/easybuild/easyblocks/e/easybuildmeta.py
  test/framework/sandbox/easybuild/easyblocks/generic/makecp.py
Labels: enhancement

#3583 fix failing GitHub tests due to trivial change in output of 'eb' command
  .github/workflows/unit_tests.yml
  test/framework/options.py
Labels: bug fix

#3586 include %(mpi_cmd_prefix)s and %(cuda_*)s templates in output of --avail-easyconfig-templates
  easybuild/framework/easyconfig/templates.py
  easybuild/tools/docs.py
  test/framework/easyconfig.py
  test/framework/options.py
Labels: bug fix, documentation

#3584 fix BLAS_LIB_MT for OpenBLAS
  easybuild/toolchains/linalg/openblas.py
  test/framework/toolchain.py
Labels: bug fix

#3506 Specifying False for a version removes the dep
  easybuild/framework/easyconfig/easyconfig.py
Labels: enhancement

#3587 update release notes + bump version for EasyBuild v4.3.3
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: documentation, update

#3589 use 'main' rather than 'master' branch in GitHub integration functionality
  easybuild/tools/github.py
  test/framework/filetools.py
  test/framework/github.py
  test/framework/options.py
  test/framework/toy_build.py
Labels: change

#3591 sync with main branch + bump version to 4.3.4dev
  RELEASE_NOTES
  easybuild/tools/github.py
  easybuild/tools/version.py
  test/framework/filetools.py
  test/framework/github.py
  test/framework/options.py
  test/framework/toy_build.py
Labels: update

#3592 add pick_default_branch function to clean up duplicate code in tools/github.py
  easybuild/tools/github.py
  test/framework/github.py
Labels: code cleanup

#3594 use '--opt=val' for passing settings from config file to option parser to avoid error for values starting with '-' or '--'
  easybuild/base/generaloption.py
  test/framework/config.py
Labels: bug fix

#3599 avoid raised exception when getting output from interactive command in run_cmd_qa
  easybuild/tools/run.py
  test/framework/run.py
Labels: bug fix
