Repository easybuilders/easybuild-framework, pull requests merged in 2021-05, with the labels that each got.

#3649 Re-enable write permissions when installing with read-only-installdir
  easybuild/framework/easyblock.py
  test/framework/options.py
  test/framework/toy_build.py
Labels: bug fix

#3651 Allow amending easyconfig parameters which are not the default
  easybuild/framework/easyconfig/default.py
  easybuild/framework/easyconfig/tweak.py
  test/framework/easyconfig.py
Labels: enhancement

#3670 add support for using ARCH constant in easyconfig files
  easybuild/framework/easyconfig/constants.py
  test/framework/easyconfig.py
  test/framework/options.py
Labels: enhancement

#3645 Don't skip sanity check for --module-only --rebuild
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix, change

#3668 move disable_templating function into the EasyConfig class
  contrib/hooks/hpc2n_hooks.py
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
Labels: code cleanup

#3674 honor keyboard interrupt in 'eb' command
  eb
Labels: enhancement

#3675 Pin GitPython version for Python<3.6, don't test bootstrap script against Python 3.8/3.9
  .github/workflows/bootstrap_script.yml
  requirements.txt
Labels: bug fix, tests

#3650 Allow for overriding RPATH with higher priority paths
  easybuild/framework/easyblock.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/toy_build.py
Labels: EESSI, enhancement

#3555 Performance improvements for easyconfig parsing and eb startup
  easybuild/base/generaloption.py
  easybuild/framework/easyconfig/templates.py
  easybuild/toolchains/linalg/libsci.py
  easybuild/tools/run.py
  easybuild/tools/toolchain/mpi.py
  easybuild/tools/toolchain/toolchain.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/modules.py
  test/framework/options.py
  test/framework/toolchain.py
Labels: performance, tests

#3680 avoid picking up easyblocks outside of sandbox in framework tests
  test/framework/options.py
  test/framework/utilities.py
Labels: bug fix

#3665 add support for using oneAPI versions of 'intel' toolchain components
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/toolchains/fft/intelfftw.py
  easybuild/toolchains/iimpi.py
  easybuild/toolchains/linalg/intelmkl.py
  test/framework/easyconfig.py
Labels: enhancement

#3681 suggest missing SSH key when not able to read from remote repository in --check-github
  easybuild/tools/github.py
Labels: change

#3678 extend sanity check step to check whether specific libraries are not linked into installed binaries/libraries
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  easybuild/toolchains/linalg/flexiblas.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  easybuild/tools/systemtools.py
  easybuild/tools/toolchain/toolchain.py
  test/framework/easyconfigs/test_ecs/l/libtoy/libtoy-0.0.eb
  test/framework/filetools.py
  test/framework/options.py
  test/framework/sandbox/easybuild/easyblocks/l/__init__.py
  test/framework/sandbox/easybuild/easyblocks/l/libtoy.py
  test/framework/sandbox/sources/l/libtoy/libtoy-0.0.tar.gz
  test/framework/systemtools.py
  test/framework/toy_build.py
Labels: enhancement

#3682 add locate_solib function to locate Linux shared libraries
  easybuild/tools/systemtools.py
  test/framework/systemtools.py
Labels: enhancement

#3683 add system agnostic function to locate shared libraries
  easybuild/tools/systemtools.py
  test/framework/systemtools.py
Labels: enhancement

#3559 avoid metadata greedy behaviour when probing for external module metadata
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: bug fix, cray

#3686 update HierarchicalMNS to also return 'Toolchain/<name>/<version>' as $MODULEPATH extension for cpe* Cray toolchains
  easybuild/tools/module_naming_scheme/hierarchical_mns.py
  test/framework/easyconfigs/test_ecs/c/cpeGNU/cpeGNU-21.04.eb
  test/framework/filetools.py
  test/framework/module_generator.py
Labels: bug fix, cray

#3685 use unload/load in ModuleGeneratorLua.swap_module, since 'swap' is not supported by Lmod
  easybuild/tools/module_generator.py
  test/framework/module_generator.py
Labels: bug fix, cray

#3684 add update_build_option function to update specific build options after initializing the EasyBuild configuration
  easybuild/tools/config.py
  test/framework/config.py
Labels: enhancement

#3679 tweak foss toolchain definition to switch from OpenBLAS to FlexiBLAS in foss/2021a
  easybuild/toolchains/foss.py
Labels: change

#3689 allow opting out of recursively unloaded of modules via recursive_module_unload easyconfig parameter
  easybuild/framework/easyconfig/default.py
  easybuild/tools/module_generator.py
  test/framework/easyconfig.py
  test/framework/options.py
Labels: enhancement

#3692 make get_config_obj return a copy rather than a reference
  easybuild/framework/easyconfig/format/one.py
  easybuild/framework/easyconfig/format/yeb.py
  test/framework/easyconfig.py
  test/framework/easyconfigparser.py
  test/framework/yeb.py
Labels: bug fix

#3693 check for correct version values when parsing easystack file
  easybuild/framework/easystack.py
  test/framework/easystack.py
  test/framework/easystacks/test_easystack_basic.yaml
  test/framework/easystacks/test_easystack_labels.yaml
  test/framework/options.py
  test/framework/suite.py
Labels: easystack, enhancement

#3696 run post-install commands specified for a specific extension
  easybuild/framework/easyblock.py
  easybuild/framework/extension.py
  test/framework/toy_build.py
Labels: enhancement

#3605 add support for multiple PRs in --from-pr
  easybuild/framework/easyconfig/tools.py
  easybuild/main.py
  easybuild/tools/filetools.py
  easybuild/tools/options.py
  easybuild/tools/testing.py
  test/framework/filetools.py
  test/framework/options.py
  test/framework/sandbox/easybuild/easyblocks/generic/pythonbundle.py
Labels: enhancement

#3677 add toolchain definition for Fujitsu ARM toolchain
  easybuild/toolchains/compiler/fujitsu.py
  easybuild/toolchains/fcc.py
  easybuild/toolchains/ffmpi.py
  easybuild/toolchains/fft/fftw.py
  easybuild/toolchains/fft/fujitsufftw.py
  easybuild/toolchains/fujitsu.py
  easybuild/toolchains/linalg/fujitsussl.py
  easybuild/toolchains/mpi/fujitsumpi.py
Labels: Fujitsu, enhancement

#3698 make sure that $TAPE is unset when using piped tar
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix

#3637 Deprecate adding a non-existing path to $MODULEPATH
  easybuild/framework/easyblock.py
  easybuild/tools/filetools.py
  easybuild/tools/modules.py
  easybuild/tools/toolchain/toolchain.py
  test/framework/easyconfig.py
  test/framework/filetools.py
  test/framework/modules.py
Labels: change

#3699 fix extending message for changed files in new_pr_from_branch
  easybuild/tools/github.py
Labels: bug fix

#3655 add support for --sanity-check-only + also run sanity check for extensions when using --module-only
  easybuild/framework/easyblock.py
  easybuild/main.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/options.py
  test/framework/toy_build.py
Labels: enhancement

#3701 enhance sched_getaffinity function to avoid early crash when counting available cores on systems with more than 1024 cores
  easybuild/tools/systemtools.py
  test/framework/systemtools.py
Labels: bug fix, enhancement

#3702 add support for --skip-extensions
  easybuild/framework/easyblock.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/options.py
  test/framework/toy_build.py
Labels: enhancement

#3704 set LDFLAGS instead of LIBRARY_PATH and add new `required` keyword to `_get_software_root` for Fujitsu toolchain
  easybuild/toolchains/compiler/fujitsu.py
  easybuild/toolchains/linalg/fujitsussl.py
Labels: change

#3705 correctly strip extension from filename in extract_cmd and back_up_file functions
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix

#3706 include PR title in output produced by --merge-pr
  easybuild/tools/github.py
Labels: enhancement

#3707 fix support for specifying multiple PRs to --from-pr
  easybuild/framework/easyconfig/tools.py
  easybuild/tools/config.py
  easybuild/tools/github.py
  easybuild/tools/options.py
  easybuild/tools/robot.py
  test/framework/options.py
  test/framework/robot.py
Labels: bug fix

#3708 fix crash in create_test_report with --upload-test-report --from-pr when one or more test installations failed
  easybuild/tools/testing.py
  test/framework/github.py
Labels: bug fix

#3714 add Fujitsu compiler lib* subdir to both $LIBRARY_PATH and $LDFLAGS
  easybuild/toolchains/compiler/fujitsu.py
Labels: change

#3713 move -Nclang back to $C[XX]FLAGS in toolchain support for Fujitsu compiler
  easybuild/toolchains/compiler/fujitsu.py
Labels: change

#3712 don't use a different module name for FFTW in the Fujitsu toolchain
  easybuild/toolchains/fft/fujitsufftw.py
Labels: change

#3715 drop support for Python 2.6
  easybuild/tools/systemtools.py
  test/framework/systemtools.py
Labels: change
