Repository easybuilders/easybuild-framework, pull requests merged in 2021-06, with the labels that each got.

#3717 only add fujitsu libdir to LIBRARY_PATH if it's not already there
  easybuild/toolchains/compiler/fujitsu.py
Labels: Fujitsu, bug fix

#3719 prepare release notes for EasyBuild v4.4.0 + bump version to 4.4.0
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3723 sync with main + bump version to 4.4.1dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3724 avoid overwritting pr_nr in post_pr_test_report for reports with --in…
  easybuild/tools/testing.py
Labels: bug fix

#3726 enhance test for post_pr_test_report to cover combination of --from-pr and --include-easyblocks-from-pr
  easybuild/framework/easyconfig/tools.py
  easybuild/tools/github.py
  easybuild/tools/options.py
  easybuild/tools/testing.py
  test/framework/github.py
Labels: enhancement, tests

#3731 parse C standard flags in CFLAGS for fujitsu compiler
  easybuild/toolchains/compiler/fujitsu.py
Labels: Fujitsu, bug fix

#3733 Fix error message for --use-ccache
  easybuild/tools/toolchain/toolchain.py
  test/framework/toolchain.py
Labels: bug fix

#3728 Add module-write hook
  easybuild/framework/easyblock.py
  easybuild/tools/hooks.py
  test/framework/toy_build.py
Labels: enhancement

#3716 Add per-step timing information
  easybuild/framework/easyblock.py
  easybuild/tools/utilities.py
  test/framework/options.py
  test/framework/toy_build.py
  test/framework/utilities_test.py
Labels: enhancement

#3729 fix crash in get_config_dict when copying modules that were imported in easyconfig file (like 'import os')
  easybuild/framework/easyconfig/format/one.py
  test/framework/easyconfig.py
Labels: bug fix

#3709 Enhance detection of patch files with better error messages
  easybuild/framework/easyconfig/tools.py
  test/framework/easyconfig.py
  test/framework/github.py
Labels: enhancement

#3730 make sure that tests requiring a github token have 'github' in the test name so that they can be easily filtered
  test/framework/github.py
  test/framework/options.py
  test/framework/robot.py
Labels: change, tests

#3741 minor fixes to output of test reports
  easybuild/tools/testing.py
Labels: bug fix

#3742 deprecate EasyBuild bootstrap script
  .github/workflows/bootstrap_script.yml
  easybuild/scripts/bootstrap_eb.py
Labels: change

#3745 fix location for modules installed with intel-compilers toolchain in HierarchicalMNS by always checking toolchain compiler name against template map
  easybuild/tools/module_naming_scheme/hierarchical_mns.py
  test/framework/easyconfigs/test_ecs/i/iimpi/iimpi-2021a.eb
  test/framework/easyconfigs/test_ecs/i/imkl/imkl-2021.2.0-iimpi-2021a.eb
  test/framework/easyconfigs/test_ecs/i/impi/impi-2021.2.0-intel-compilers-2021.2.0.eb
  test/framework/easyconfigs/test_ecs/i/intel-compilers/intel-compilers-2021.2.0.eb
  test/framework/filetools.py
  test/framework/module_generator.py
  test/framework/options.py
Labels: bug fix

#3755 use temporary download folder in test_http_header_fields_urlpat
  test/framework/options.py
Labels: tests

#3756 avoid checking msg attribute of GitCommandError
  easybuild/tools/github.py
Labels: bug fix

#3735 add toolchain nvompic
  easybuild/toolchains/nvompic.py
Labels: enhancement
