Repository easybuilders/easybuild-framework, pull requests merged in 2021-03, with the labels that each got.

#3600 add support for using fallback 'arch=*' key in dependency version specified as arch->version mapping
  easybuild/tools/systemtools.py
  test/framework/easyconfig.py
  test/framework/systemtools.py
Labels: enhancement, tests

#3604 also check for pending change requests and mergeable_state in check_pr_eligible_to_merge
  easybuild/tools/github.py
  test/framework/github.py
  test/framework/options.py
Labels: enhancement

#3607 ignore undismissed 'changes requested' review if there is an 'approved' review by the same user
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#3608 filter duplicates in changes_requested_by
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#3610 enhance 'eb' command to ensure that easybuild.main can be imported before settling on python* command to use
  .github/workflows/eb_command.yml
  eb
Labels: enhancement

#3609 Sort output of eb --search in natural order (respecting numbers)
  easybuild/tools/filetools.py
  easybuild/tools/utilities.py
  test/framework/easyblock.py
  test/framework/filetools.py
  test/framework/options.py
  test/framework/robot.py
  test/framework/suite.py
  test/framework/utilities_test.py
Labels: enhancement

#3613 added configuration option to define the env command to use for shebangs
  easybuild/framework/easyblock.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/toy_build.py
Labels: enhancement

#3614 Add option to write file from file-like object and use in download_file
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix

#3616 Refactor the CI configuration to use inclusion instead of exclusion
  .github/workflows/unit_tests.yml
Labels: code cleanup, tests, update
