Repository easybuilders/easybuild-framework, pull requests merged in 2021-08, with the labels that each got.

#3798 fix CI by excluding GC3Pie 2.6.7 (which is broken with Python 2) and improve error reporting for option parsing
  easybuild/tools/options.py
  requirements.txt
Labels: bug fix

#3799 check type of source_tmpl value for extensions, ensure it's a string value (not a list)
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: enhancement

#3786 Don't parse patch files as easyconfigs when searching for where patch file is used
  easybuild/tools/github.py
  test/framework/github.py
Labels: enhancement, bug fix

#3800 also define $BLAS_SHARED_LIBS & co in build environment (analogous to $BLAS_STATIC_LIBS)
  easybuild/toolchains/fft/fftw.py
  easybuild/tools/toolchain/constants.py
  easybuild/tools/toolchain/fft.py
  easybuild/tools/toolchain/linalg.py
  easybuild/tools/toolchain/variables.py
  test/framework/toolchain.py
Labels: enhancement

#3806 report use of --ignore-test-failure in success message in output
  easybuild/main.py
  test/framework/toy_build.py
Labels: enhancement

#3796 add --filter-ecs options to filter out easyconfigs from set of easyconfigs to install
  easybuild/framework/easyconfig/tools.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/robot.py
Labels: enhancement

#3736 add toolchain nvpsmpic
  easybuild/toolchains/nvpsmpic.py
Labels: enhancement

#3802 speed up tests by caching checked paths in set_tmpdir + less test cases for test_compiler_dependent_optarch
  easybuild/tools/options.py
  test/framework/toolchain.py
Labels: bug fix, performance

#3807 add get_cuda_cc_template_value method to EasyConfig class
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: enhancement

#3734 Add per-extension timing
  easybuild/framework/easyblock.py
Labels: enhancement

#3771 Make logdir writable also when --stop/--fetch is given
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/tools/modules.py
  test/framework/toy_build.py
  test/framework/utilities.py
Labels: bug fix

#3784 Check for recursive symlinks by default before copying a folder
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: enhancement

#3813 add --easystack to ignore_opts for submit_job()
  easybuild/tools/parallelbuild.py
Labels: bug fix
