Repository easybuilders/easybuild-framework, pull requests merged in 2022-01, with the labels that each got.

#3920 deprecate use of patch files that don't have a filename ending with .patch
  easybuild/tools/filetools.py
  test/framework/easyconfig.py
  test/framework/filetools.py
Labels: change

#3923 add support for update_build_options + enhance update_build_options to return original value
  easybuild/tools/config.py
  test/framework/config.py
Labels: enhancement

#3925 remove version restriction for keyring in requirements.txt to test with latest version
  .github/workflows/unit_tests.yml
  requirements.txt
Labels: update, tests

#3926 fix compatibility with Python 3.10
  .github/workflows/unit_tests.yml
  easybuild/base/frozendict.py
  easybuild/tools/ordereddict.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  test/framework/easyconfig.py
Labels: enhancement, bug fix

#3928 use sources.easybuild.io as backup URL for downloading Environment Modules sources to run test suite
  easybuild/scripts/install_eb_dep.sh
Labels: bug fix, tests

#3927 simplify requirements.txt by removing python 2.6 support
  requirements.txt
Labels: code cleanup

#3931 enhance get_cpu_architecture and get_cpu_family to be aware of RISC-V
  easybuild/tools/systemtools.py
Labels: enhancement

#3929 make intelfftw toolchain component aware of GCCcore
  easybuild/toolchains/fft/intelfftw.py
Labels: enhancement

#3933 also run tests for 'eb' command with Python 3.10
  .github/workflows/eb_command.yml
Labels: enhancement, tests

#3930 also take /etc/os-release into account in get_os_name and get_os_version
  easybuild/tools/systemtools.py
Labels: enhancement

#3935 prepare release notes for EasyBuild v4.5.2 + bump version to 4.5.2
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3938 only run GitHub tests when testing with Lua module syntax, to avoid hitting GitHub rate limit when running tests
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
Labels: bug fix, tests

#3937 release EasyBuild v4.5.2
  .github/workflows/eb_command.yml
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/base/frozendict.py
  easybuild/framework/easyblock.py
  easybuild/scripts/install_eb_dep.sh
  easybuild/toolchains/fft/intelfftw.py
  easybuild/tools/config.py
  easybuild/tools/filetools.py
  easybuild/tools/ordereddict.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  easybuild/tools/systemtools.py
  easybuild/tools/version.py
  requirements.txt
  test/framework/config.py
  test/framework/easyconfig.py
  test/framework/filetools.py
  test/framework/toy_build.py
Labels: update

#3939 initialize BACKUP_PKG_URL with empty string
  easybuild/scripts/install_eb_dep.sh
Labels: bug fix

#3942 Fix get_os_name and get_os_version
  easybuild/tools/systemtools.py
Labels: bug fix

#3936 take into account that patch files can also be zipped when checking filename extension for patches
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix

#3944 consistently use actions/setup-python@v2 in CI workflows
  .github/workflows/linting.yml
Labels: bug fix
