Repository easybuilders/easybuild-framework, pull requests merged in 2022-09, with the labels that each got.

#4048 run python in the same process as `eb` wrapper script by using `exec`
  easybuild/main.py
  eb
Labels: change, performance

#4068 fix `quote_str` when string with both ' and " ends with a double quote
  easybuild/tools/utilities.py
  test/framework/easyconfig.py
Labels: bug fix

#4051 add get_linked_libs_raw function, and use it from both check_linked_shared_libs and sanity_check_rpath
  easybuild/framework/easyblock.py
  easybuild/tools/systemtools.py
Labels: bug fix, code cleanup

#4063 ensure we call EasyBlock.patch_step for postinstallpatches
  easybuild/framework/easyblock.py
Labels: bug fix

#4071 relax toolchain test by accepting both -march=native (x86_64) and -mcpu=native (aarch64)
  test/framework/options.py
  test/framework/toolchain.py
Labels: bug fix, aarch64, tests

#4066 fix leaked handles in set_columns, complete_cmd, run_cmd_qa, det_terminal_size functions + tests
  easybuild/base/generaloption.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  easybuild/tools/run.py
  easybuild/tools/systemtools.py
  test/framework/asyncprocess.py
  test/framework/run.py
  test/framework/toy_build.py
Labels: bug fix

#4070 fix type-checking of patches to allow dict values + correctly handle patches specified as dict values in --new-pr
  easybuild/framework/easyconfig/types.py
  easybuild/tools/github.py
  test/framework/options.py
  test/framework/type_checking.py
Labels: bug fix

#4075 prepare release notes for EasyBuild v4.6.1 + bump version to 4.6.1
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4077 release EasyBuild 4.6.1
  .github/workflows/bootstrap_script.yml
  .github/workflows/container_tests.yml
  .github/workflows/eb_command.yml
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/base/fancylogger.py
  easybuild/base/generaloption.py
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/one.py
  easybuild/framework/easyconfig/format/version.py
  easybuild/framework/easyconfig/types.py
  easybuild/main.py
  easybuild/scripts/findPythonDeps.py
  easybuild/tools/config.py
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  easybuild/tools/modules.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  easybuild/tools/run.py
  easybuild/tools/systemtools.py
  easybuild/tools/utilities.py
  easybuild/tools/version.py
  eb
  requirements.txt
  test/framework/asyncprocess.py
  test/framework/easyconfig.py
  test/framework/options.py
  test/framework/run.py
  test/framework/toolchain.py
  test/framework/toy_build.py
  test/framework/type_checking.py
Labels: update

#4078 sync with main + bump version to 4.6.2dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4081 Make scripts executable
  easybuild/scripts/bootstrap_eb.py
  easybuild/scripts/clean_gists.py
  easybuild/scripts/fix_docs.py
  easybuild/scripts/mk_tmpl_easyblock_for.py
Labels: change

#4080 skip over unset $EB_PYTHON/$EB_INSTALLPYTHON
  .github/workflows/eb_command.yml
  eb
Labels: enhancement

#4076 make check_sha256_checksums verify all checksums if they're specified as a dict value
  easybuild/framework/easyblock.py
  test/framework/easyconfig.py
Labels: bug fix
