Repository easybuilders/easybuild-framework, pull requests merged in 2022-04, with the labels that each got.

#3993 consider installed modules when using --copy-ec without --rebuild
  easybuild/main.py
Labels: change

#3995 Change 'eb' command to import easybuild to check if it's working.
  .github/workflows/eb_command.yml
  eb
Labels: enhancement

#3999 ignore deprecation warnings regarding cryptography in Python 3.6 + Blowfish with Python 3.10 in test suite output
  .github/workflows/unit_tests.yml
Labels: bug fix, tests

#3969 add nvompi toolchain definition (NVHPC + OpenMPI)
  easybuild/toolchains/nvompi.py
Labels: enhancement

#3970 add nvpsmpi toolchain definition (NVHPC + ParaStationMPI)
  easybuild/toolchains/nvpsmpi.py
Labels: enhancement

#4000 fix typo in debug log message in easyblock.py
  easybuild/framework/easyblock.py
Labels: bug fix
