Repository easybuilders/easybuild-framework, pull requests merged in 2022-11, with the labels that each got.

#4121 add `fdefault-double-8` to `r8` toolchain compiler option for GCC (to be consistent with Intel)
  easybuild/toolchains/compiler/gcc.py
  test/framework/toolchain.py
Labels: bug fix, change

#4118 tweak findPythonDeps.py to use canonical package names
  easybuild/scripts/findPythonDeps.py
Labels: bug fix

#4123 use new EasyBuild logo in README
  README.rst
Labels: update, documentation

#3749 add support for checksums specified in external `checksums.json` file
  easybuild/framework/easyblock.py
  easybuild/main.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/easyblock.py
  test/framework/easyconfigs/test_ecs/t/toy/checksums.json
  test/framework/filetools.py
  test/framework/module_generator.py
  test/framework/options.py
Labels: enhancement

#4112 add explicit return when no checksums match those specified in a tuple
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix

#4057 take into account custom configuration options specified in easystack file + drop support for easystack files using 'software' top-level key
  easybuild/framework/easystack.py
  easybuild/main.py
  easybuild/tools/options.py
  test/framework/easystack.py
  test/framework/easystacks/test_easystack_asterisk.yaml
  test/framework/easystacks/test_easystack_basic.yaml
  test/framework/easystacks/test_easystack_basic_dict.yaml
  test/framework/easystacks/test_easystack_easyconfigs.yaml
  test/framework/easystacks/test_easystack_easyconfigs_dict.yaml
  test/framework/easystacks/test_easystack_easyconfigs_opts.yaml
  test/framework/easystacks/test_easystack_easyconfigs_str.yaml
  test/framework/easystacks/test_easystack_invalid_key.yaml
  test/framework/easystacks/test_easystack_invalid_key2.yaml
  test/framework/easystacks/test_easystack_labels.yaml
  test/framework/easystacks/test_easystack_wrong_structure.yaml
  test/framework/easystacks/test_missing_easyconfigs_key.yaml
  test/framework/options.py
Labels: enhancement, change, easystack

#4108 fix build options that should have empty list as default value
  easybuild/tools/config.py
  test/framework/config.py
Labels: bug fix

#4109 catch easyconfig parsing failure so we can generate and post a test report
  easybuild/main.py
  easybuild/tools/testing.py
  test/framework/toy_build.py
Labels: bug fix

#4129 correct uses of :param name: and :return: in docstrings
  easybuild/base/fancylogger.py
  easybuild/base/generaloption.py
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/style.py
  easybuild/framework/extension.py
  easybuild/tools/build_log.py
  easybuild/tools/run.py
  easybuild/tools/systemtools.py
Labels: documentation

#4130 docstrings - fixes to formatting or variables names
  easybuild/base/generaloption.py
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  easybuild/tools/modules.py
  easybuild/tools/multidiff.py
  easybuild/tools/repository/gitrepo.py
  easybuild/tools/repository/hgrepo.py
  easybuild/tools/repository/repository.py
  easybuild/tools/repository/svnrepo.py
  easybuild/tools/run.py
Labels: documentation

#4132 Cancel old GithubAction runs
  .github/workflows/bootstrap_script.yml
  .github/workflows/container_tests.yml
  .github/workflows/eb_command.yml
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
Labels: enhancement
