Repository easybuilders/easybuild-framework, pull requests merged in 2022-03, with the labels that each got.

#3949 add support for 'clone_into' field in git_config source spec to specify different name for top-level directory
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: enhancement

#3971 add gmpit toolchain definition (GCC + MPItrampoline)
  easybuild/toolchains/gmpit.py
  easybuild/toolchains/mpi/mpitrampoline.py
  easybuild/tools/toolchain/mpi.py
Labels: enhancement

#3967 add a 'sync pr' message when the PR has a mergeable state but is showing a failed status for the test suite on the last commit
  easybuild/tools/github.py
Labels: enhancement

#3974 add support for post-install patches
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  test/framework/sandbox/sources/toy/toy-0.0_fix-README.patch
  test/framework/toy_build.py
Labels: enhancement

#3976 Added new parameter key to specify some download or installation steps for user in case of complicated way of obtaining needed files
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  test/framework/easyblock.py
Labels: enhancement

#3978 add support for collecting GPU info (via rocm-smi)
  easybuild/tools/systemtools.py
Labels: enhancement

#3981 also print download instructions for extensions that use source_tmpl to specify name of source file
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: bug fix

#3973 use 'zypper search -i' to check whether specified OS dependency is installed on openSUSE + make sure that rpm is considered for checking OS dependencies on RHEL8
  easybuild/tools/systemtools.py
Labels: enhancement

#3982 enhance GPU info (via rocm-smi): report card series in addition
  easybuild/tools/systemtools.py
Labels: enhancement

#3985 run 'apt-get update' in GitHub Actions workflow for container tests to update container package list before installing anything
  .github/workflows/container_tests.yml
Labels: bug fix, tests

#3979 ensure --review-pr can find dependencies included in PR
  easybuild/framework/easyconfig/tools.py
  easybuild/tools/options.py
Labels: bug fix

#3983 prepare release notes for EasyBuild v4.5.4 + bump version to 4.5.4
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3989 sync with main + bump version to 4.5.5dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update
