Repository easybuilders/easybuild-framework, pull requests merged in 2022-08, with the labels that each got.

#4049 fix code style issues reported by recent flake8 linter
  easybuild/base/fancylogger.py
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/format/version.py
  easybuild/tools/filetools.py
  easybuild/tools/modules.py
Labels: bug fix, code cleanup, tests

#4053 add 'ai' default module class
  easybuild/tools/config.py
Labels: enhancement

#4055 stick to autopep8<1.7.0 with Python 2.7
  requirements.txt
Labels: bug fix, tests

#4069 use SYSTEM constant for dependency that uses system toolchain in dumped easyconfig
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/one.py
  test/framework/easyconfig.py
Labels: change
