Repository easybuilders/easybuild-framework, pull requests merged in 2022-07, with the labels that each got.

#4030 add support for setting environment variables via 'pushenv' with modextravars
  .github/workflows/bootstrap_script.yml
  .github/workflows/container_tests.yml
  .github/workflows/eb_command.yml
  .github/workflows/unit_tests.yml
  easybuild/tools/module_generator.py
  test/framework/easyblock.py
  test/framework/sandbox/easybuild/easyblocks/generic/toy_extension.py
Labels: enhancement

#4038 tweak apply_patch to not create .orig files (by default) when applying patch files
  easybuild/tools/config.py
  easybuild/tools/filetools.py
  easybuild/tools/options.py
  test/framework/easyblock.py
  test/framework/filetools.py
Labels: change

#4036 add support for using template values in name/version of extensions
  easybuild/framework/easyblock.py
  test/framework/easyconfig.py
Labels: enhancement

#4019 tweak eb wrapper script to correctly handle errors when python command being considered fails to run
  eb
Labels: bug fix, code cleanup

#4039 don't use -ftz for Intel oneAPI compilers versions before 2022.x
  easybuild/toolchains/compiler/intel_compilers.py
  test/framework/modules.py
  test/framework/modules/intel-compilers/2022.1.0
  test/framework/toolchain.py
Labels: bug fix

#4041 prepare release notes for EasyBuild v4.6.0 + bump version to 4.6.0
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4042 release EasyBuild v4.6.0
  .github/workflows/bootstrap_script.yml
  .github/workflows/container_tests.yml
  .github/workflows/eb_command.yml
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/constants.py
  easybuild/toolchains/compiler/intel_compilers.py
  easybuild/tools/config.py
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  easybuild/tools/module_generator.py
  easybuild/tools/options.py
  easybuild/tools/systemtools.py
  easybuild/tools/version.py
  eb
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/filetools.py
  test/framework/github.py
  test/framework/module_generator.py
  test/framework/modules.py
  test/framework/modules/intel-compilers/2022.1.0
  test/framework/sandbox/easybuild/easyblocks/generic/toy_extension.py
  test/framework/sandbox/sources/alt_toy
  test/framework/systemtools.py
  test/framework/toolchain.py
Labels: update

#4043 sync with main + bump version to 4.6.1dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3839 Add script to find dependencies of Python packages
  easybuild/scripts/findPythonDeps.py
Labels: enhancement
