Repository easybuilders/easybuild-framework, pull requests merged in 2022-10, with the labels that each got.

#4085 Make inject_checksums inject dictionaries
  easybuild/framework/easyblock.py
  test/framework/options.py
Labels: enhancement, change

#4090 skip GitPython 3.1.28, since it prints 'git' as version which messes up the version check in check_github()
  requirements.txt
Labels: bug fix, tests

#4091 make sure that GitPython version is a proper version before checking minimal required version
  easybuild/tools/github.py
  requirements.txt
Labels: bug fix

#4089 update to v3 of actions/checkout and actions/setup-python in CI workflows
  .github/workflows/bootstrap_script.yml
  .github/workflows/container_tests.yml
  .github/workflows/eb_command.yml
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
Labels: update, tests

#4087 add `%(cuda_cc_cmake)s` template
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
Labels: enhancement

#4021 add support for easystack file that contains easyconfig filenames + implement parsing of configuration options
  easybuild/framework/easystack.py
  easybuild/main.py
  test/framework/easystack.py
  test/framework/easystacks/test_easystack_easyconfigs.yaml
  test/framework/easystacks/test_easystack_easyconfigs_opts.yaml
  test/framework/easystacks/test_easystack_easyconfigs_with_eb_ext.yaml
Labels: enhancement, easystack

#4094 use SYSTEM template constant in dependencies instead of True in framework tests
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/easyconfigs/test_ecs/b/binutils/binutils-2.25-GCCcore-4.9.3.eb
  test/framework/easyconfigs/test_ecs/b/binutils/binutils-2.26-GCCcore-4.9.3.eb
  test/framework/easyconfigs/test_ecs/g/gzip/gzip-1.4-GCC-4.6.3.eb
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-deps.eb
Labels: code cleanup, tests

#4093 first look for patch in alt_location when it is specified
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: priority:critical, bug fix

#4088 Fix trying to generate RPATH wrappers for Clang
  easybuild/tools/toolchain/toolchain.py
  test/framework/toolchain.py
Labels: bug fix

#4099 prepare release notes for EasyBuild v4.6.2 + bump version to 4.6.2
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4100 release EasyBuild 4.6.2
  .github/workflows/bootstrap_script.yml
  .github/workflows/container_tests.yml
  .github/workflows/eb_command.yml
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/templates.py
  easybuild/framework/easystack.py
  easybuild/main.py
  easybuild/scripts/bootstrap_eb.py
  easybuild/scripts/clean_gists.py
  easybuild/scripts/fix_docs.py
  easybuild/scripts/mk_tmpl_easyblock_for.py
  easybuild/tools/github.py
  easybuild/tools/toolchain/toolchain.py
  easybuild/tools/version.py
  eb
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/easyconfigs/test_ecs/b/binutils/binutils-2.25-GCCcore-4.9.3.eb
  test/framework/easyconfigs/test_ecs/b/binutils/binutils-2.26-GCCcore-4.9.3.eb
  test/framework/easyconfigs/test_ecs/g/gzip/gzip-1.4-GCC-4.6.3.eb
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-deps.eb
  test/framework/easystack.py
  test/framework/easystacks/test_easystack_easyconfigs.yaml
  test/framework/easystacks/test_easystack_easyconfigs_opts.yaml
  test/framework/easystacks/test_easystack_easyconfigs_with_eb_ext.yaml
  test/framework/options.py
  test/framework/sandbox/sources/alt_toy
  test/framework/sandbox/sources/alt_toy/toy-0.0.tar.gz
  test/framework/sandbox/sources/alt_toy/toy-0.0_fix-silly-typo-in-printf-statement.patch
  test/framework/toolchain.py
Labels: update

#4101 sync with main + bump version to 4.6.3dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4107 also use EasyConfig instances cache in process_easyconfig when build_specs is empty dict
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
  test/framework/utilities.py
Labels: bug fix
