Repository easybuilders/easybuild-framework, pull requests merged in 2022-06, with the labels that each got.

#4011 set $FFT(W)_LIB_DIR to imkl-FFTW's lib path in build environment if usempi toolchain option is enabled
  easybuild/toolchains/fft/intelfftw.py
  test/framework/toolchain.py
Labels: bug fix

#4012 Support FFTW.MPI module in framework (FFT*DIR variables)
  easybuild/toolchains/fft/fftw.py
  test/framework/modules.py
  test/framework/modules/FFTW.MPI/3.3.7
  test/framework/modules/FFTW/3.3.7
  test/framework/modules/foss/2018a-FFTW.MPI
  test/framework/toolchain.py
Labels: enhancement

#4020 prepare release notes for EasyBuild v4.5.5 + bump version to 4.5.5
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4023 release EasyBuild v4.5.5
  .github/workflows/eb_command.yml
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/main.py
  easybuild/toolchains/fft/fftw.py
  easybuild/toolchains/fft/intelfftw.py
  easybuild/toolchains/gfbf.py
  easybuild/toolchains/nvompi.py
  easybuild/toolchains/nvpsmpi.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  easybuild/tools/parallelbuild.py
  easybuild/tools/systemtools.py
  easybuild/tools/version.py
  eb
  test/framework/easyblock.py
  test/framework/modules.py
  test/framework/modules/FFTW.MPI/3.3.7
  test/framework/modules/FFTW/3.3.7
  test/framework/modules/foss/2018a-FFTW.MPI
  test/framework/parallelbuild.py
  test/framework/systemtools.py
  test/framework/toolchain.py
Labels: update

#4024 sync with main + bump version to 4.5.6dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4018 make sure that ARCH constant has 'aarch64' (rather than 'arm64') as value on macOS ARM
  easybuild/framework/easyconfig/constants.py
  easybuild/tools/systemtools.py
  test/framework/easyconfig.py
Labels: bug fix

#4026 show URLs used for download attempts in trace output
  easybuild/tools/filetools.py
Labels: enhancement

#4027 update Lmod used to run tests to version 8.7.4
  .github/workflows/bootstrap_script.yml
  .github/workflows/container_tests.yml
  .github/workflows/eb_command.yml
  .github/workflows/unit_tests.yml
  test/framework/module_generator.py
Labels: update, tests

#4028 tweak is_patch_for function to make it more robust
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#4032 add dedicated test for opting in to using oneAPI Intel compilers
  test/framework/toolchain.py
Labels: enhancement, tests

#4033 make check_linked_shared_libs more robust by taking into account that 'ldd' may fail
  easybuild/tools/systemtools.py
  test/framework/systemtools.py
Labels: enhancement
