Repository easybuilders/easybuild-framework, pull requests merged in 2022-02, with the labels that each got.

#3940 indicate compatibility with Python 3.10 in setup.py
  setup.py
Labels: update, documentation

#3947 specify easybuild.io as EasyBuild homepage in setup.py
  setup.py
Labels: bug fix, documentation

#3954 also check for git in --check-eb-deps
  easybuild/tools/systemtools.py
Labels: enhancement

#3955 avoid crash in get_os_version on modern SLES-based OSs
  easybuild/tools/systemtools.py
  test/framework/systemtools.py
Labels: bug fix

#3945 switch to using pip3 for installing EasyBuild in Singularity definition file generated by EasyBuild
  easybuild/tools/config.py
  easybuild/tools/containers/docker.py
  easybuild/tools/containers/singularity.py
  test/framework/containers.py
Labels: bug fix

#3958 add end2end test for 'eb --containerize'
  .github/workflows/container_tests.yml
Labels: enhancement, tests

#3960 prepare release notes for EasyBuild v4.5.3 + bump version to 4.5.3
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3953 Add bash completion for easyconfigs from local dir but not robot search path
  eb_bash_completion_local.bash
Labels: enhancement

#3964 sync with main + bump version to 4.5.4dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#3759 warn about potentially missing patches in --new-pr
  easybuild/tools/github.py
Labels: enhancement

#3966 Only check for patches when using --new-pr if easyconfigs repository is target
  easybuild/tools/github.py
  test/framework/options.py
Labels: bug fix

#3725 enable code linting check for all supported Python versions
  .github/workflows/linting.yml
  easybuild/framework/easyblock.py
  easybuild/tools/configobj.py
Labels: code cleanup, tests
