Repository easybuilders/easybuild-framework, pull requests merged in 2023-02, with the labels that each got.

#4166 fix use of `locate` in `check_os_dependency`
  easybuild/tools/systemtools.py
Labels: bug fix

#4201 print warning when non-existing `start_dir` is specified for extension
  easybuild/framework/extensioneasyblock.py
  test/framework/easyblock.py
Labels: enhancement

#4209 skip directories when fixing shebangs
  easybuild/framework/easyblock.py
  test/framework/toy_build.py
Labels: enhancement

#4213 restore initial environment before processing each easystack item
  easybuild/main.py
  test/framework/easystack.py
Labels: bug fix, easystack

#4184 check type of versionsuffix value in det_full_ec_version, and raise useful error message if it's not a string
  easybuild/tools/module_naming_scheme/utilities.py
  test/framework/easyconfig.py
  test/framework/module_generator.py
Labels: bug fix

#4144 allow to directly import constants from easybuild.framework.easyconfig.constants
  easybuild/framework/easyconfig/constants.py
  test/framework/easyconfig.py
Labels: enhancement

#3845 Add option to make sanity_check_paths arch dependent
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/types.py
  easybuild/tools/systemtools.py
  test/framework/easyblock.py
  test/framework/systemtools.py
  test/framework/type_checking.py
Labels: enhancement

#4205 Replace more usages of assertTrue/False
  easybuild/base/testing.py
  test/framework/build_log.py
  test/framework/config.py
  test/framework/containers.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/easyconfigparser.py
  test/framework/filetools.py
  test/framework/github.py
  test/framework/hooks.py
  test/framework/include.py
  test/framework/lib.py
  test/framework/license.py
  test/framework/modules.py
  test/framework/modulestool.py
  test/framework/options.py
  test/framework/output.py
  test/framework/parallelbuild.py
  test/framework/repository.py
  test/framework/robot.py
  test/framework/run.py
  test/framework/systemtools.py
  test/framework/toolchain.py
  test/framework/toy_build.py
Labels: code cleanup, tests

#4220 Only print "default: " for str-list options if it is not empty.
  easybuild/base/generaloption.py
Labels: change

#4073 add support for start_dir easyconfig template
  easybuild/framework/easyconfig/templates.py
  easybuild/framework/extension.py
  easybuild/framework/extensioneasyblock.py
  test/framework/easyconfig.py
  test/framework/sandbox/easybuild/easyblocks/generic/toy_extension.py
  test/framework/sandbox/easybuild/easyblocks/t/toy.py
Labels: enhancement

#4207 Add option to silence deprecation warning of ECs and toolchains
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/main.py
  easybuild/tools/config.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  test/framework/easyconfig.py
Labels: enhancement, change

#4193 add pre/post extension hook (triggered before/after individual extension installations)
  easybuild/framework/easyblock.py
  easybuild/tools/hooks.py
  test/framework/hooks.py
  test/framework/options.py
  test/framework/toy_build.py
Labels: enhancement
