Repository easybuilders/easybuild-framework, pull requests merged in 2023-06, with the labels that each got.

#4271 Add script to find updated ECs for installed modules
  easybuild/scripts/findUpdatedEcs.sh
Labels: enhancement

#4250 enable --trace by default
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/easystack.py
  test/framework/filetools.py
  test/framework/github.py
  test/framework/lib.py
  test/framework/modules.py
  test/framework/options.py
  test/framework/package.py
  test/framework/parallelbuild.py
  test/framework/repository.py
  test/framework/robot.py
  test/framework/run.py
  test/framework/systemtools.py
  test/framework/toolchain.py
  test/framework/toy_build.py
Labels: EasyBuild-5.0

#4253 Use version suffixes in PR title instead of Python versions when using --new-pr
  easybuild/tools/github.py
  test/framework/github.py
Labels: enhancement, change

#4286 fix broken GitHub tests
  test/framework/options.py
Labels: bug fix
