Repository easybuilders/easybuild-framework, pull requests merged in 2023-08, with the labels that each got.

#4287 suggest default title in `--review-pr`
  easybuild/framework/easyconfig/tools.py
Labels: enhancement

#4306 copy `load_source` function from `easybuild.tools.py2vs3.py3` to `easybuild.tools.filetools` so it can be used `easybuild.tools.hooks`
  easybuild/tools/filetools.py
  easybuild/tools/hooks.py
  easybuild/tools/py2vs3/py3.py
  test/framework/filetools.py
Labels: bug fix

#4311 fix broken github tests in options `test.framework.options` by disabling trace output in `download_repo` and `fetch_files_from_pr` functions
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  test/framework/filetools.py
Labels: bug fix, tests, EasyBuild-5.0

#4310 disable trace output for commands run in `get_source_tarball_from_git`
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug fix, tests, EasyBuild-5.0

#4309 use sys.executable to obtain path to `python` command, rather than assuming that `python` command is available in `$PATH`
  test/framework/run.py
Labels: bug fix, tests

#4312 fix `test_add_and_remove_module_path` by replacing string comparison onf paths by checking whether they point to the same path (since symlinks may cause trouble)
  test/framework/modules.py
Labels: bug fix, tests

#4284 initial implementation of `run` function to replace `run_cmd` + `run_cmd_qa`
  easybuild/tools/run.py
  test/framework/run.py
Labels: enhancement, code cleanup, EasyBuild-5.0

#4304 Implement `build_and_install_loop` hooks to run before and after the install loop for individual modules
  easybuild/main.py
  easybuild/tools/hooks.py
  test/framework/options.py
Labels: enhancement

#4316 add postiter hook to the list of steps so the corresponding hook can be used
  easybuild/tools/hooks.py
  test/framework/options.py
Labels: enhancement

#4314 implement `fail_on_error`/`in_dry_run`/`output_file` options + enable caching for `run` function, and switch from `run_cmd` to `run` function in systemtools
  easybuild/tools/run.py
  easybuild/tools/systemtools.py
  test/framework/run.py
  test/framework/systemtools.py
Labels: enhancement, change, EasyBuild-5.0

#4308 Ignore request for external module (meta)data when no modules tool is active
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/options.py
Labels: bug fix

#4321 implement support in `run` function for splitting stdout and stderr output + passing down environment to use, and switch to `run` function for running `module` commands
  easybuild/tools/modules.py
  easybuild/tools/run.py
  test/framework/modules.py
  test/framework/run.py
Labels: enhancement, change, EasyBuild-5.0

#4315 Implement hooks for failure scenarios
  easybuild/main.py
  easybuild/tools/hooks.py
  test/framework/options.py
Labels: enhancement

#4324 add `build_info_msg` easyconfig parameter
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  test/framework/toy_build.py
Labels: enhancement

#4323 add `run_shell_cmd` hook
  easybuild/tools/hooks.py
  easybuild/tools/options.py
  easybuild/tools/run.py
  easybuild/tools/systemtools.py
  test/framework/hooks.py
  test/framework/options.py
  test/framework/run.py
  test/framework/sandbox/easybuild/easyblocks/t/toy.py
  test/framework/toy_build.py
Labels: enhancement

#4322 also include command used + working directory in return value of `run` function
  easybuild/tools/run.py
  test/framework/run.py
  test/framework/systemtools.py
Labels: enhancement, change, EasyBuild-5.0

#4328 don't use `FileExistsError` in `mkdir` function (doesn't exist in Python 2.7)
  easybuild/tools/filetools.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  test/framework/filetools.py
Labels: bug fix

#4327 implement support in '`run`' function for running command in different working directory + switch to `run` function in filetools
  easybuild/tools/filetools.py
  easybuild/tools/run.py
  test/framework/filetools.py
  test/framework/lib.py
  test/framework/run.py
  test/framework/toy_build.py
Labels: enhancement, change, EasyBuild-5.0

#4334 trigger `run_shell_cmd` hook in `run` function
  easybuild/tools/filetools.py
  easybuild/tools/hooks.py
  easybuild/tools/run.py
  easybuild/tools/systemtools.py
  test/framework/filetools.py
  test/framework/run.py
  test/framework/toy_build.py
Labels: enhancement, EasyBuild-5.0

#3968 add end-to-end test for running EasyBuild in different Linux distros using containers
  .github/workflows/end2end.yml
Labels: enhancement, tests

#4335 rename `run` function to `run_shell_cmd`
  easybuild/tools/filetools.py
  easybuild/tools/modules.py
  easybuild/tools/run.py
  easybuild/tools/systemtools.py
  test/framework/lib.py
  test/framework/modules.py
  test/framework/run.py
  test/framework/systemtools.py
Labels: change, EasyBuild-5.0

#4336 rename `run_cache` decorator to `run_shell_cmd_cache`
  easybuild/tools/run.py
Labels: change, EasyBuild-5.0

#4337 add definitions for ifbf and iofbf toolchain
  easybuild/toolchains/ifbf.py
  easybuild/toolchains/iofbf.py
Labels: enhancement

#4329 add `--silence-hook-trigger` configuration option to supress printing of debug message every time a hook is triggered
  easybuild/tools/config.py
  easybuild/tools/hooks.py
  easybuild/tools/options.py
  test/framework/hooks.py
Labels: enhancement

#4332 add support for using fine grained Github tokens
  easybuild/tools/github.py
  test/framework/github.py
Labels: enhancement

#4331 only add extensions in module file if there are extensions
  easybuild/tools/module_generator.py
  test/framework/module_generator.py
Labels: bug fix
