Repository easybuilders/easybuild-framework, pull requests merged in 2023-07, with the labels that each got.

#4290 fix regex for extracting glibc version from output of '`ldd --version`' in Gentoo Linux
  easybuild/tools/systemtools.py
  test/framework/systemtools.py
Labels: bug fix, EESSI

#4292 allow versionsuffix to be set to None in `det_full_ec_version`
  easybuild/tools/module_naming_scheme/utilities.py
  test/framework/easyconfig.py
Labels: bug fix

#4270 update `check_python_version` to reflect that only Python >= 3.6 is supported
  easybuild/tools/systemtools.py
  test/framework/systemtools.py
  test/framework/toolchain.py
Labels: code cleanup, EasyBuild-5.0

#4293 prepare release notes for EasyBuild v4.8.0 + bump version to 4.8.0
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update, documentation

#4294 release EasyBuild v4.8.0
  .github/workflows/container_tests.yml
  .github/workflows/container_tests_apptainer.yml
  .github/workflows/eb_command.yml
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/scripts/findUpdatedEcs.sh
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  easybuild/tools/hooks.py
  easybuild/tools/module_naming_scheme/utilities.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/py2vs3/py3.py
  easybuild/tools/systemtools.py
  easybuild/tools/version.py
  test/framework/easyconfig.py
  test/framework/github.py
  test/framework/options.py
  test/framework/systemtools.py
Labels: update

#4295 sync with main + bump version to 4.8.1dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4272 remove support for 32-bit targets
  easybuild/toolchains/compiler/clang.py
  easybuild/toolchains/compiler/gcc.py
  easybuild/toolchains/compiler/inteliccifort.py
  easybuild/toolchains/fcc.py
  easybuild/toolchains/linalg/acml.py
  easybuild/toolchains/linalg/intelmkl.py
  easybuild/tools/toolchain/compiler.py
  easybuild/tools/toolchain/mpi.py
  easybuild/tools/toolchain/toolchain.py
Labels: code cleanup, EasyBuild-5.0
