Repository easybuilders/easybuild-framework, pull requests merged in 2023-12, with the labels that each got.

#4395 use source toolchain version when passing only `--try-toolchain`
  easybuild/tools/options.py
  test/framework/easyconfigs/test_ecs/i/iimpi/iimpi-2018a.eb
  test/framework/easyconfigs/test_ecs/i/intel/intel-2018a.eb
  test/framework/filetools.py
  test/framework/options.py
Labels: bug fix

#4386 eliminate duplicate multideps from generated module files
  easybuild/tools/module_generator.py
Labels: bug fix

#4379 fix `LIBBLAS_MT` for FlexiBLAS, ensure `-lpthread` is included
  easybuild/toolchains/linalg/flexiblas.py
  test/framework/modules.py
  test/framework/modules/FFTW.MPI/3.3.10-gompi-2023a
  test/framework/modules/FFTW/3.3.10-GCC-12.3.0
  test/framework/modules/FlexiBLAS/3.3.1-GCC-12.3.0
  test/framework/modules/GCC/12.3.0
  test/framework/modules/GCCcore/12.3.0
  test/framework/modules/OpenBLAS/0.3.23-GCC-12.3.0
  test/framework/modules/OpenMPI/4.1.5-GCC-12.3.0
  test/framework/modules/PMIx/4.2.4-GCCcore-12.3.0
  test/framework/modules/ScaLAPACK/2.2.0-gompi-2023a-fb
  test/framework/modules/UCC/1.2.0-GCCcore-12.3.0
  test/framework/modules/UCX/1.14.1-GCCcore-12.3.0
  test/framework/modules/binutils/2.40-GCCcore-12.3.0
  test/framework/modules/foss/2023a
  test/framework/modules/gompi/2023a
  test/framework/modules/hwloc/2.9.1-GCCcore-12.3.0
  test/framework/modules/libevent/2.1.12-GCCcore-12.3.0
  test/framework/modules/libfabric/1.18.0-GCCcore-12.3.0
  test/framework/modules/zlib/1.2.13-GCCcore-12.3.0
  test/framework/toolchain.py
Labels: bug fix

#3669 allow tweaking of easyconfigs from different toolchains
  easybuild/framework/easyconfig/tweak.py
  test/framework/easyconfig.py
Labels: enhancement

#4408 fix LooseVersion on Python 2.7
  easybuild/tools/loose_version.py
  test/framework/utilities_test.py
Labels: bug fix

#4405 fix `--inject-checksums` when extension specifies patch file in tuple format
  easybuild/framework/easyblock.py
  test/framework/options.py
Labels: bug fix

#4403 add `--module-cache-suffix` configuration setting to allow multiple (Lmod) caches
  easybuild/tools/config.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
Labels: enhancement

#4402 fix writing spider cache for Lmod >= 8.7.12
  easybuild/tools/modules.py
Labels: bug fix

#4385 relax major version match regex in `find_related_easyconfigs` using for `--review-pr`
  easybuild/framework/easyconfig/tools.py
Labels: bug fix, change

#4392 resolve templated values in extension names in `_make_extension_list`
  easybuild/framework/easyblock.py
Labels: bug fix

#4371 Adapt module function check for Environment Modules v4+
  easybuild/tools/modules.py
  easybuild/tools/run.py
  test/framework/modulestool.py
Labels: bug fix

#4414 use more recent easyblocks PR in `test_github_merge_pr`
  test/framework/options.py
Labels: bug fix, tests

#4152 add support for --list-software --output-format=json
  easybuild/tools/docs.py
  easybuild/tools/options.py
  test/framework/docs.py
Labels: enhancement

#4419 prepare release notes for EasyBuild v4.9.0 + bump version to 4.9.0
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update, documentation

#4420 release EasyBuild v4.9.0
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/tools.py
  easybuild/framework/easyconfig/tweak.py
  easybuild/toolchains/compiler/intel_compilers.py
  easybuild/toolchains/linalg/flexiblas.py
  easybuild/tools/config.py
  easybuild/tools/docs.py
  easybuild/tools/loose_version.py
  easybuild/tools/module_generator.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  easybuild/tools/run.py
  easybuild/tools/version.py
  test/framework/docs.py
  test/framework/easyconfig.py
  test/framework/easyconfigs/test_ecs/i/iimpi/iimpi-2018a.eb
  test/framework/easyconfigs/test_ecs/i/intel/intel-2018a.eb
  test/framework/filetools.py
  test/framework/modules.py
  test/framework/modules/FFTW.MPI/3.3.10-gompi-2023a
  test/framework/modules/FFTW/3.3.10-GCC-12.3.0
  test/framework/modules/FlexiBLAS/3.3.1-GCC-12.3.0
  test/framework/modules/GCC/12.3.0
  test/framework/modules/GCCcore/12.3.0
  test/framework/modules/OpenBLAS/0.3.23-GCC-12.3.0
  test/framework/modules/OpenMPI/4.1.5-GCC-12.3.0
  test/framework/modules/PMIx/4.2.4-GCCcore-12.3.0
  test/framework/modules/ScaLAPACK/2.2.0-gompi-2023a-fb
  test/framework/modules/UCC/1.2.0-GCCcore-12.3.0
  test/framework/modules/UCX/1.14.1-GCCcore-12.3.0
  test/framework/modules/binutils/2.40-GCCcore-12.3.0
  test/framework/modules/foss/2023a
  test/framework/modules/gompi/2023a
  test/framework/modules/hwloc/2.9.1-GCCcore-12.3.0
  test/framework/modules/libevent/2.1.12-GCCcore-12.3.0
  test/framework/modules/libfabric/1.18.0-GCCcore-12.3.0
  test/framework/modules/zlib/1.2.13-GCCcore-12.3.0
  test/framework/modulestool.py
  test/framework/options.py
  test/framework/run.py
  test/framework/toolchain.py
  test/framework/utilities_test.py
Labels: update

#4421 sync with main + bump version to 4.9.1dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update
