Repository easybuilders/easybuild-framework, pull requests merged in 2023-10, with the labels that each got.

#4352 fix parallellisation typo
  easybuild/toolchains/compiler/gcc.py
  easybuild/tools/options.py
  easybuild/tools/systemtools.py
  test/framework/easyblock.py
  test/framework/systemtools.py
Labels: bug fix

#4351 improve error reporting for failing shell commands (and EasyBuild crashes)
  easybuild/framework/easyblock.py
  easybuild/main.py
  easybuild/tools/build_log.py
  easybuild/tools/hooks.py
  easybuild/tools/run.py
  test/framework/build_log.py
  test/framework/hooks.py
  test/framework/options.py
  test/framework/run.py
  test/framework/systemtools.py
  test/framework/toy_build.py
Labels: enhancement, EasyBuild-5.0

#4355 minor help fix
  easybuild/tools/options.py
Labels: bug fix

#4358 use 5.0.x branch for easyblocks + easyconfigs in CI workflows (for now)
  .github/workflows/container_tests.yml
  .github/workflows/container_tests_apptainer.yml
  .github/workflows/end2end.yml
Labels: change, tests, EasyBuild-5.0

#4357 take into account that `VERBOSE_VERSION` imported from `easybuild.easyblocks` is now a string value
  easybuild/tools/version.py
Labels: bug fix, EasyBuild-5.0

#4359 add support for `%(sysroot)s` template value
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
Labels: enhancement, EESSI

#4360 add `dependency_names` method to `EasyConfig` class to get set of names of (direct) dependencies
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: enhancement

#4365 fix `findPythonDeps.py` script when called with an absolute path to an easyconfig
  easybuild/scripts/findPythonDeps.py
Labels: bug fix

#4366 fix broken test for `reasons_for_closing`, which fails because commit status of easyconfigs PR is no longer available
  test/framework/github.py
Labels: bug fix, tests

#4367 prepare release notes for EasyBuild v4.8.2 + bump version to 4.8.2
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4370 release EasyBuild v4.8.2
  .github/workflows/unit_tests.yml
  .github/workflows/unit_tests_python2.yml
  RELEASE_NOTES
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/templates.py
  easybuild/main.py
  easybuild/scripts/findPythonDeps.py
  easybuild/toolchains/compiler/gcc.py
  easybuild/tools/docs.py
  easybuild/tools/options.py
  easybuild/tools/systemtools.py
  easybuild/tools/version.py
  test/framework/docs.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/easystack.py
  test/framework/github.py
  test/framework/options.py
  test/framework/systemtools.py
  test/framework/toy_build.py
Labels: update
