Repository easybuilders/easybuild-framework, pull requests merged in 2024-09, with the labels that each got.

#4591 Use default value `$XDG_CONFIG_DIRS` from XDG basedir spec: `/etc/xdg` (instead of `/etc`)
  easybuild/tools/options.py
  test/framework/options.py
Labels: bug fix, change, EasyBuild-5.0

#4623 Remove a superflous check in `EasyBlock.run_all_steps`
  easybuild/framework/easyblock.py
Labels: code cleanup

#4620 only call `_sanity_check_step_extensions` if `--skip-extensions` is not set
  easybuild/framework/easyblock.py
Labels: enhancement

#4415 Run unit tests on an updated versions of Modules: v4.5.3 + v5.3.1
  .github/workflows/unit_tests.yml
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/toolchain.py
  test/framework/toy_build.py
Labels: bug fix, tests, EasyBuild-5.0

#4626 allow for case where `homepage = None` when generating the docs
  easybuild/tools/docs.py
Labels: bug fix

#4625 derive `EnvironmentModules` class directly from `ModulesTool` rather than from to be deprecated `EnvironmentModulesTcl`
  easybuild/tools/config.py
  easybuild/tools/module_generator.py
  easybuild/tools/modules.py
  test/framework/module_generator.py
  test/framework/modules.py
  test/framework/modulestool.py
  test/framework/options.py
  test/framework/utilities.py
Labels: code cleanup, EasyBuild-5.0

#4624 move verifying of checksums from `source` to `fetch` step, to include it with `--fetch`
  easybuild/framework/easyblock.py
  test/framework/options.py
Labels: change, EasyBuild-5.0

#4425 bump minimum required Tmod (4.x) to 4.3.0
  easybuild/tools/modules.py
Labels: change, EasyBuild-5.0, EasyBuild-5.0-blocker

#4628 Add support for `--software-commit` and an associated template `%(software_commit)s`
  easybuild/framework/easyconfig/templates.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/easyconfig.py
  test/framework/options.py
Labels: enhancement

#4079 add support for `--extra-source-urls` to fetch sources from additional URLs
  easybuild/base/generaloption.py
  easybuild/framework/easyblock.py
  easybuild/tools/config.py
  easybuild/tools/options.py
Labels: enhancement

#4632 Remove trailing dots from backup message produced by `--inject-checksums`
  easybuild/framework/easyblock.py
  test/framework/options.py
Labels: change

#4631 prepare release notes for EasyBuild v4.9.3 + bump version to 4.9.3
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update, documentation

#4636 fix `test_github_det_commit_status` by using more recent commits
  test/framework/github.py
Labels: bug fix, tests

#4635 release EasyBuild v4.9.3
  .github/workflows/end2end.yml
  .github/workflows/unit_tests.yml
  .github/workflows/unit_tests_python2.yml
  RELEASE_NOTES
  easybuild/base/generaloption.py
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/templates.py
  easybuild/framework/easyconfig/tools.py
  easybuild/main.py
  easybuild/toolchains/compiler/gcc.py
  easybuild/toolchains/compiler/intel_compilers.py
  easybuild/toolchains/gmpflf.py
  easybuild/toolchains/linalg/intelmkl.py
  easybuild/tools/build_details.py
  easybuild/tools/config.py
  easybuild/tools/docs.py
  easybuild/tools/filetools.py
  easybuild/tools/options.py
  easybuild/tools/output.py
  easybuild/tools/py2vs3/py2.py
  easybuild/tools/systemtools.py
  easybuild/tools/version.py
  eb
  requirements.txt
  test/framework/easyconfig.py
  test/framework/filetools.py
  test/framework/github.py
  test/framework/modules.py
  test/framework/modules/intel-compilers/2024.0.0
  test/framework/options.py
  test/framework/repository.py
  test/framework/toolchain.py
Labels: update

#4638 sync with main + bump version to 4.9.4dev
  RELEASE_NOTES
  easybuild/tools/version.py
  test/framework/github.py
Labels: update

#4639 sync with develop (20240915)
  RELEASE_NOTES
  easybuild/base/generaloption.py
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/main.py
  easybuild/tools/config.py
  easybuild/tools/docs.py
  easybuild/tools/filetools.py
  easybuild/tools/options.py
  test/framework/easyconfig.py
  test/framework/filetools.py
  test/framework/github.py
  test/framework/options.py
  test/framework/toolchain.py
Labels: update, EasyBuild-5.0

#4646 take into account alternate sysroot for `/bin/bash` used by `run_cmd`
  easybuild/tools/options.py
  easybuild/tools/run.py
  easybuild/tools/systemtools.py
  test/framework/run.py
Labels: bug fix, EESSI

#4642 implement workaround for permission error when copying read-only files that have extended attributes set and using Python 3.6
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: bug report, bug fix

#4648 set `$LMOD_TERSE_DECORATIONS` to '`no`' to avoid additional info in output produced by '`ml --terse avail`'
  easybuild/tools/modules.py
Labels: enhancement

#4649 prepare release notes for EasyBuild v4.9.4 + bump version to 4.9.4
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4650 release EasyBuild v4.9.4
  RELEASE_NOTES
  easybuild/tools/filetools.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  easybuild/tools/run.py
  easybuild/tools/systemtools.py
  easybuild/tools/version.py
  test/framework/filetools.py
  test/framework/run.py
Labels: update

#4651 sync with main + bump version to 4.9.5dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4654 sync with develop (20240923)
  RELEASE_NOTES
  easybuild/_deprecated.py
  easybuild/tools/filetools.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  test/framework/filetools.py
  test/framework/run.py
Labels: update, EasyBuild-5.0

#4633 fix `findPythonDeps.py` script for cyclic dependencies
  easybuild/scripts/findPythonDeps.py
Labels: bug fix

#4658 resolve symlink when making log dir writable
  easybuild/framework/easyblock.py
Labels: bug fix
