Repository easybuilders/easybuild-framework, pull requests merged in 2024-07, with the labels that each got.

#4568 fix fetch progress bar showing to many files
  easybuild/framework/easyblock.py
Labels: bug fix

#4554 Correctly evaluate result for `--dep-graph`
  easybuild/framework/easyconfig/tools.py
Labels: bug fix

#4574 CI: Allow using Node 16 actions
  .github/workflows/end2end.yml
  .github/workflows/unit_tests_python2.yml
Labels: bug fix, tests

#4571 fix definition of gmpflf toolchain
  easybuild/toolchains/gmpflf.py
Labels: bug fix

#4569 reuse pre-computed checksums
  easybuild/framework/easyblock.py
  easybuild/tools/filetools.py
  test/framework/filetools.py
Labels: enhancement

#4583 Add cuda_cc_space_sep variant that does not have periods
  .github/workflows/unit_tests.yml
  easybuild/framework/easyconfig/templates.py
  test/framework/easyconfig.py
Labels: enhancement

#4576 don't use special flags for `strict`, `precise`, `loose`, `veryloose` toolchain options on RISC-V
  easybuild/toolchains/compiler/gcc.py
Labels: bug fix, EESSI, riscv
