Repository easybuilders/easybuild-framework, pull requests merged in 2024-06, with the labels that each got.

#4486 create `env.sh` and `cmd.sh` helper scripts in `run_shell_cmd`
  easybuild/tools/run.py
  test/framework/run.py
  test/framework/toy_build.py
Labels: enhancement, EasyBuild-5.0

#4546 sync with develop (20240605)
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: EasyBuild-5.0

#4537 add support for easyconfig parameter `module_only`
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  test/framework/options.py
Labels: enhancement

#4520 versions checks to avoid mixing major versions across the EasyBuild components
  easybuild/main.py
  easybuild/tools/github.py
  easybuild/tools/version.py
Labels: enhancement

#4514 add renamed alternate constants/templates/parameters
  easybuild/framework/easyconfig/parser.py
  easybuild/framework/easyconfig/templates.py
Labels: EasyBuild-5.0, EasyBuild-5.0-blocker

#4544 trigger pre-hook in `run_shell_cmd` as early as possible so dry-run + trace output is correct
  easybuild/tools/run.py
  test/framework/run.py
Labels: bug fix, EasyBuild-5.0, EasyBuild-5.0-blocker

#4551 also consider `$CRAY_PE_LIBSCI_PREFIX_DIR` to determine installation prefix for cray-libsci
  easybuild/toolchains/linalg/libsci.py
Labels: bug fix

#4513 enhance `get_software_libdir` to return `lib` or `lib64` if only one of them contains library files
  easybuild/tools/modules.py
  test/framework/modules.py
Labels: enhancement

#4553 don't try to determine repo version when file that contains version doesn't exist
  easybuild/tools/github.py
Labels: bug fix

#4555 Use "alternative" instead of "alternate"
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/easyconfig.py
  easybuild/framework/easyconfig/format/pyheaderconfigobj.py
  easybuild/framework/easyconfig/parser.py
  easybuild/framework/easyconfig/templates.py
  easybuild/framework/easyconfig/tweak.py
  easybuild/toolchains/compiler/craype.py
  easybuild/tools/filetools.py
  easybuild/tools/toolchain/toolchain.py
  test/framework/easyblock.py
  test/framework/easyconfig.py
  test/framework/toolchain.py
  test/framework/toy_build.py
Labels: EasyBuild-5.0

#4557 prepare release notes for EasyBuild v4.9.2 + bump version to 4.9.2
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update, documentation

#4562 sync with main + bump version to 4.9.3dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4549 include alternative names of easyconfig parameters in output of `--avail-easyconfig-params`
  easybuild/tools/docs.py
Labels: enhancement, EasyBuild-5.0

#4564 sync with develop (20240619)
  RELEASE_NOTES
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  easybuild/main.py
  easybuild/toolchains/linalg/libsci.py
  easybuild/tools/github.py
  easybuild/tools/modules.py
  easybuild/tools/version.py
  test/framework/modules.py
  test/framework/options.py
Labels: update, EasyBuild-5.0

#4566 add definition for gmpflf toolchain
  easybuild/toolchains/gmpflf.py
Labels: enhancement
