Repository easybuilders/easybuild-framework, pull requests merged in 2025-04, with the labels that each got.

#4833 Delete .coveragerc
  .coveragerc
Labels: code cleanup

#4830 Fix tests after removal of 5.0.x branch
  test/framework/github.py
  test/framework/options.py
Labels: bug fix, tests

#4839 Wrong variable name used for Python version in linting CI
  .github/workflows/linting.yml
Labels: bug fix

#4841 Fix failing GitHub integration CI tests
  test/framework/easyconfigs/test_ecs/g/GCC/GCC-10.2.0.eb
  test/framework/filetools.py
  test/framework/github.py
  test/framework/options.py
  test/framework/tweak.py
Labels: bug fix, tests

#4845 fix testsuite badge
  README.rst
Labels: bug fix, tests

#4847 Avoid failure when only some passed easyconfigs exist
  easybuild/framework/easyconfig/tools.py
Labels: bug fix

#4842 take into account `job-output-dir` option in Slurm job backend
  easybuild/tools/job/slurm.py
Labels: bug fix

#4850 Add "-" before "DMKL_ILP64" CFLAGS
  easybuild/toolchains/linalg/intelmkl.py
Labels: bug fix

#4843 Fix unbound variable in error case in `build_and_install_software`
  easybuild/main.py
Labels: bug fix

#4806 Fix `check_checksums` when `nosource: True` is used.
  easybuild/framework/easyblock.py
  test/framework/easyconfig.py
Labels: bug fix

#4596 allow specifying location for RPATH wrapper scripts via `rpath_wrappers_dir` + also pass `rpath_include_dirs` when preparing build environment for extensions
  easybuild/framework/easyblock.py
  easybuild/scripts/rpath_wrapper_template.sh.in
  easybuild/tools/toolchain/toolchain.py
  test/framework/toolchain.py
Labels: enhancement, bug fix

#4861 print summary after the build in trace output
  easybuild/main.py
Labels: enhancement
