Repository easybuilders/easybuild-framework, pull requests merged in 2025-07, with the labels that each got.

#4915 Change value of architectures constants RISCV32 and RISCV64
  easybuild/tools/systemtools.py
Labels: change, riscv

#4947 Fix logic for `pr_repo` used in `--sync-pr-with-develop`
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#4919 add total iteration count to trace output
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: enhancement

#4899 Update install-EasyBuild-develop.sh to allow installation without forking
  easybuild/scripts/install-EasyBuild-develop.sh
Labels: enhancement

#4950 prepare release notes for EasyBuild v5.1.1 + bump version to 5.1.1
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4954 fix broken tests for GitHub integration features
  test/framework/docs.py
  test/framework/github.py
  test/framework/options.py
  test/framework/sandbox/easybuild/easyblocks/b/blis.py
Labels: bug fix, tests

#4955 sync with main + bump version to 5.1.2dev
  RELEASE_NOTES
  easybuild/tools/version.py
  test/framework/docs.py
  test/framework/github.py
  test/framework/options.py
  test/framework/sandbox/easybuild/easyblocks/b/blis.py
Labels: update

#4965 add back `OrderedDict` import in (deprecated) `easybuild.tools.py2vs3.py3` module
  easybuild/tools/py2vs3/py3.py
Labels: bug fix
