Repository easybuilders/easybuild-framework, pull requests merged in 2025-08, with the labels that each got.

#4971 Honor 'module_extensions' build option
  easybuild/tools/module_generator.py
  test/framework/module_generator.py
Labels: bug fix

#4958 Do not fail for read-only installation directory on `--module-only` (re)builds
  easybuild/framework/easyblock.py
Labels: bug fix, change

#4972 Add support for "extensions" on Tcl modulefiles
  easybuild/tools/module_generator.py
  easybuild/tools/modules.py
  easybuild/tools/options.py
  test/framework/module_generator.py
Labels: enhancement

#4973 Adapt module_extensions disable test for Tcl modulefiles
  test/framework/module_generator.py
Labels: bug fix, tests

#4970 Fix RPATH wrapper by detecting & replacing `-Xlinker --enable-new-dtags`
  easybuild/scripts/rpath_args.py
  test/framework/toolchain.py
Labels: bug fix

#4976 Exit with appropriate error code for `--search` when no match is found
  easybuild/main.py
  test/framework/options.py
Labels: enhancement

#4980 Handle `post_install_patches` and `post_install_msgs` for extensions
  easybuild/framework/easyblock.py
  easybuild/framework/extension.py
  test/framework/toy_build.py
Labels: enhancement
