Repository easybuilders/easybuild-framework, pull requests merged in 2025-06, with the labels that each got.

#4913 Add `required` argument to `get_cuda_cc_template_value`
  easybuild/framework/easyconfig/easyconfig.py
  test/framework/easyconfig.py
Labels: enhancement

#4923 add support for pre/post `easyblock` hook
  easybuild/framework/easyblock.py
  easybuild/tools/hooks.py
  test/framework/hooks.py
  test/framework/options.py
  test/framework/toy_build.py
Labels: enhancement

#4920 Fix reporting of method name in `EasyBlock.run_step`
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: bug fix

#4924 Remove use of unsupported `source` key in patch spec
  easybuild/framework/easyblock.py
Labels: code cleanup

#4934 fix `TypeError: '<' not supported between instances of 'int' and 'tuple'`
  test/framework/easyblock.py
Labels: bug fix, tests

#4938 trigger `post_easyblock_hook` later
  easybuild/framework/easyblock.py
Labels: change
