Repository easybuilders/easybuild-framework, pull requests merged in 2025-05, with the labels that each got.

#4474 add support for data installations
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  easybuild/framework/easyconfig/format/format.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  test/framework/options.py
  test/framework/utilities.py
Labels: enhancement, EasyBuild-5.0

#4852 replace deprecation warning about reproducible tarballs on Python older than 3.9 to a regular warning
  easybuild/framework/easyblock.py
Labels: change

#4873 count the `data_sources`
  easybuild/framework/easyconfig/easyconfig.py
Labels: bug fix

#4874 include `data_sources` when checking checksums
  easybuild/framework/easyblock.py
Labels: bug fix

#4875 use full words in summary
  easybuild/main.py
Labels: enhancement

#4865 Fix `is_patch_for` for patch dicts
  easybuild/tools/github.py
  test/framework/github.py
Labels: bug fix

#4870 implement exponential backoff in `download_file` + allow max. 6 attempts to download PR diff in `fetch_files_from_pr` and `fetch_files_from_commit`
  easybuild/tools/config.py
  easybuild/tools/filetools.py
  easybuild/tools/github.py
  test/framework/filetools.py
Labels: bug fix

#4880 only wait in `download_file` when it makes sense to wait (when HTTP status 429 was found)
  easybuild/tools/filetools.py
Labels: bug fix

#4879 use `develop` branch for PRs that target removed `5.0.x` branch in `fetch_files_from_pr`
  easybuild/tools/github.py
Labels: bug fix

#4848 restore original value for non-list easyconfig parameter values that are considered for iterating over
  easybuild/framework/easyblock.py
  test/framework/easyblock.py
Labels: bug fix

#4881 also ignore errors raised during test step when `--ignore-test-failure` is used
  easybuild/framework/easyblock.py
  test/framework/sandbox/easybuild/easyblocks/t/toy.py
  test/framework/toy_build.py
Labels: bug fix

#4878 obtain PR/commit diff via GitHub API rather than downloading `*.diff` file via github.com
  easybuild/tools/github.py
  test/framework/github.py
Labels: enhancement

#4868 Update fake module for each extension installed
  easybuild/framework/easyblock.py
  easybuild/framework/extensioneasyblock.py
  test/framework/easyblock.py
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-gompi-2018a-test.eb
  test/framework/options.py
  test/framework/toy_build.py
Labels: bug fix

#4858 use new `ModEnvVarType.STRICT_PATH_WITH_FILES` with `CMAKE_LIBRARY_PATH` environment variable
  easybuild/framework/easyblock.py
  easybuild/tools/modules.py
  test/framework/easyblock.py
  test/framework/toy_build.py
Labels: bug fix

#4886 Support options for patch command
  easybuild/framework/easyblock.py
  easybuild/tools/filetools.py
  test/framework/easyblock.py
  test/framework/filetools.py
Labels: enhancement

#4851 Remove superflous assignment in _sanity_check_step
  easybuild/framework/easyblock.py
Labels: code cleanup

#4692 add a CUDA device code sanity check
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  easybuild/tools/config.py
  easybuild/tools/options.py
  easybuild/tools/systemtools.py
  test/framework/systemtools.py
  test/framework/toy_build.py
Labels: enhancement, EasyBuild-5.0

#4888 check whether `exts_defaultclass` is set after call to `prepare_for_extensions`
  easybuild/framework/easyblock.py
  test/framework/easyconfigs/test_ecs/t/toy/toy-0.0-gompi-2018a-test.eb
Labels: bug fix

#4855 add support for environment variables in `set_environment` of module generators
  easybuild/tools/module_generator.py
  test/framework/easyblock.py
  test/framework/module_generator.py
  test/framework/toy_build.py
Labels: enhancement

#4859 move `EasyBlock.expand_module_search_path` into `ModuleEnvironmentVariable.expand_paths`
  easybuild/framework/easyblock.py
  easybuild/tools/modules.py
  test/framework/easyblock.py
  test/framework/modules.py
Labels: code cleanup

#4891 Fix `--dep-graph` by using `graphviz` Python package
  easybuild/framework/easyconfig/tools.py
  easybuild/tools/systemtools.py
Labels: bug fix

#4892 replace full trace message for extension check command with simple pass/fail message
  easybuild/framework/extension.py
Labels: enhancement

#4768 add support for `check_readelf_rpath` easyconfig parameter to optionally skip RPATH checks
  easybuild/framework/easyblock.py
  easybuild/framework/easyconfig/default.py
  test/framework/toy_build.py
Labels: enhancement

#4905 sync with main + bump version to 5.1.1dev
  RELEASE_NOTES
  easybuild/tools/version.py
Labels: update

#4907 add blue, cyan, purple as known colors that can be used in colorize function
  easybuild/tools/output.py
  test/framework/output.py
Labels: enhancement

#4911 also pass value of `fail_on_error` and `hidden` options of `run_shell_cmd` call down to pre/post `run_shell_cmd` hook
  easybuild/tools/run.py
  test/framework/run.py
Labels: enhancement
